-- ============================================================
-- Fynoy Capital — one-shot setup script.
-- Paste this into Supabase Dashboard -> SQL Editor and run.
--
-- This file is idempotent: it can be re-run safely.
--   1. Adds the case columns that the CSV needs (migration 005).
--   2. Relaxes tradingview_ta_score from numeric -> text (CSV has
--      "Buy" / "Sell" not numeric).
--   3. Opens cases SELECT to authenticated users so the member
--      dashboard can join positions <-> cases.
--   4. Creates the stock_prices cache table (migration 006).
--   5. Upserts all 12 cases from the source CSV.
-- ============================================================


-- ─── 1. Migration 005: cases fields + type fix + RLS ──────────

ALTER TABLE public.cases
  ADD COLUMN IF NOT EXISTS event_summary           text,
  ADD COLUMN IF NOT EXISTS event_type              text,
  ADD COLUMN IF NOT EXISTS event_classification    text,
  ADD COLUMN IF NOT EXISTS direction               text,
  ADD COLUMN IF NOT EXISTS execute                 boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS why_not_executed        text,
  ADD COLUMN IF NOT EXISTS current_price_at_case   numeric,
  ADD COLUMN IF NOT EXISTS catalyst_1              text,
  ADD COLUMN IF NOT EXISTS catalyst_2              text,
  ADD COLUMN IF NOT EXISTS catalyst_3              text,
  ADD COLUMN IF NOT EXISTS catalyst_4              text,
  ADD COLUMN IF NOT EXISTS risk_1                  text,
  ADD COLUMN IF NOT EXISTS risk_2                  text,
  ADD COLUMN IF NOT EXISTS risk_3                  text,
  ADD COLUMN IF NOT EXISTS risk_4                  text,
  ADD COLUMN IF NOT EXISTS ai_summary              text;

ALTER TABLE public.cases
  ALTER COLUMN tradingview_ta_score TYPE text USING tradingview_ta_score::text;

DROP POLICY IF EXISTS "cases: admin can select" ON public.cases;
DROP POLICY IF EXISTS "cases: authenticated can select" ON public.cases;
CREATE POLICY "cases: authenticated can select"
  ON public.cases FOR SELECT
  USING (auth.uid() IS NOT NULL);


-- ─── 2. Migration 006: stock_prices cache ─────────────────────

CREATE TABLE IF NOT EXISTS public.stock_prices (
  id         uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  symbol     text        NOT NULL,
  date       date        NOT NULL,
  close      numeric     NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(symbol, date)
);
CREATE INDEX IF NOT EXISTS stock_prices_symbol_date_idx
  ON public.stock_prices (symbol, date);

ALTER TABLE public.stock_prices ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "stock_prices: authenticated can select" ON public.stock_prices;
CREATE POLICY "stock_prices: authenticated can select"
  ON public.stock_prices FOR SELECT
  USING (auth.uid() IS NOT NULL);


-- ─── 3. Cases data — 12 UPSERTs ───────────────────────────────

-- 1. Microsoft (MSFT-406-0326)
INSERT INTO public.cases (
  trading_id, company_name, status, ticker, date_of_case, sector, country_of_incorporation,
  current_price_at_case,
  event_summary, event_type, event_classification, impact_of_news, initial_market_assessment,
  catalyst_1, catalyst_2, trigger_score,
  risk_1,
  business_model_explanation, earnings_quality, competitive_advantage,
  competitive_advantage_defined, market_position,
  esg_governance_quality_score, net_debt_ebitda, fundamental_score,
  current_pe, forward_pe, ev_ebitda, top_3_competitors, prior_valuation_assessment,
  eps, operating_margin, valuation_score,
  primary_trend, overall_chart_assessment, technical_score,
  direction, entry_price_target, take_profit, stop_loss, leverage,
  risk_reward_ratio, expected_holding_period_months,
  total_score, confidence_score, execute, created_at
) VALUES (
  'MSFT-406-0326', $F$Microsoft$F$, 'Active', 'MSFT', '2026-03-01', 'Tech', 'US',
  392.74,
  $F$Big worry about AI profitability, since november 2025$F$,
  'sentiment-driven sell-off', 'Non-recurring', 'Temporary', 'Overreaction',
  $F$Upcoming earnings release (in ~2 months) with potential upside versus analyst consensus expectations.$F$,
  $F$Potential Azure growth acceleration because of the AI boom$F$,
  5,
  $F$The entree level maybe too high, not a really good event that$F$,
  $F$Microsoft is a diversified technology company spanning productivity software, cloud infrastructure (Azure), AI solutions, enterprise software, and hardware devices.$F$,
  'High', 'Strong',
  $F$Switching costs: companies use their whole IT infrastructure on windows, microsft, Azure. Thats also whats giving them strong pricing power, brand strenght and also because of the sowftware they offer, they have strong network effects. They are a market leader in different segments$F$,
  'Leader',
  5, '2.00', 10,
  24.58, 23.75, 15.32, $F$Amazon, Alphabet, Apple$F$, 'Discounted',
  '16.00', '47.09%', 7,
  'Uptrend', 'Neutral', 2,
  'Long', 406.00, 551.00, 334.00, 0,
  2.00, 4,
  30, 7, false, '2026-04-05 21:13:00+00'
)
ON CONFLICT (trading_id) DO UPDATE SET
  company_name              = EXCLUDED.company_name,
  status                    = EXCLUDED.status,
  ticker                    = EXCLUDED.ticker,
  date_of_case              = EXCLUDED.date_of_case,
  sector                    = EXCLUDED.sector,
  country_of_incorporation  = EXCLUDED.country_of_incorporation,
  current_price_at_case     = EXCLUDED.current_price_at_case,
  event_summary             = EXCLUDED.event_summary,
  event_type                = EXCLUDED.event_type,
  event_classification      = EXCLUDED.event_classification,
  impact_of_news            = EXCLUDED.impact_of_news,
  initial_market_assessment = EXCLUDED.initial_market_assessment,
  catalyst_1                = EXCLUDED.catalyst_1,
  catalyst_2                = EXCLUDED.catalyst_2,
  trigger_score             = EXCLUDED.trigger_score,
  risk_1                    = EXCLUDED.risk_1,
  business_model_explanation = EXCLUDED.business_model_explanation,
  earnings_quality          = EXCLUDED.earnings_quality,
  competitive_advantage     = EXCLUDED.competitive_advantage,
  competitive_advantage_defined = EXCLUDED.competitive_advantage_defined,
  market_position           = EXCLUDED.market_position,
  esg_governance_quality_score = EXCLUDED.esg_governance_quality_score,
  net_debt_ebitda           = EXCLUDED.net_debt_ebitda,
  fundamental_score         = EXCLUDED.fundamental_score,
  current_pe                = EXCLUDED.current_pe,
  forward_pe                = EXCLUDED.forward_pe,
  ev_ebitda                 = EXCLUDED.ev_ebitda,
  top_3_competitors         = EXCLUDED.top_3_competitors,
  prior_valuation_assessment = EXCLUDED.prior_valuation_assessment,
  eps                       = EXCLUDED.eps,
  operating_margin          = EXCLUDED.operating_margin,
  valuation_score           = EXCLUDED.valuation_score,
  primary_trend             = EXCLUDED.primary_trend,
  overall_chart_assessment  = EXCLUDED.overall_chart_assessment,
  technical_score           = EXCLUDED.technical_score,
  direction                 = EXCLUDED.direction,
  entry_price_target        = EXCLUDED.entry_price_target,
  take_profit               = EXCLUDED.take_profit,
  stop_loss                 = EXCLUDED.stop_loss,
  leverage                  = EXCLUDED.leverage,
  risk_reward_ratio         = EXCLUDED.risk_reward_ratio,
  expected_holding_period_months = EXCLUDED.expected_holding_period_months,
  total_score               = EXCLUDED.total_score,
  confidence_score          = EXCLUDED.confidence_score,
  execute                   = EXCLUDED.execute,
  created_at                = EXCLUDED.created_at;


-- 2. Palantir (PLTR-130-0326)
INSERT INTO public.cases (
  trading_id, company_name, status, ticker, date_of_case, sector, country_of_incorporation,
  current_price_at_case,
  event_summary, event_type, event_classification, impact_of_news, initial_market_assessment,
  catalyst_1, catalyst_2, trigger_score,
  risk_1,
  business_model_explanation, earnings_quality, competitive_advantage,
  competitive_advantage_defined, market_position,
  esg_governance_quality_score, fundamental_score,
  current_pe, forward_pe, ev_ebitda, top_3_competitors, prior_valuation_assessment,
  eps, operating_margin, valuation_score,
  primary_trend, overall_chart_assessment, technical_score,
  direction, entry_price_target, take_profit, stop_loss, leverage,
  risk_reward_ratio, expected_holding_period_months,
  total_score, confidence_score, created_at
) VALUES (
  'PLTR-130-0326', $F$Palantir$F$, 'Active', 'PLTR', '2026-03-02', 'Tech', 'US',
  153.00,
  $F$Since December 2025, the stock declined ~30%, primarily driven by valuation compression after an extremely strong 2025 rally, combined with broader tech-sector weakness and profit-taking.$F$,
  'Valuation-driven correction', 'Non-recurring', 'Temporary', 'Justified',
  $F$rising global demand for defense and data-intelligence solutions because of the current(/upcoming) wars in the next months$F$,
  $F$the added AI component through AIP accelerating adoption and increasing contract value.$F$,
  5,
  $F$The stock appears overvalued at current levels, and earnings expectations are very high. If the price declines to 130, it would present a more attractive buying opportunity.$F$,
  $F$Palantir develops and sells enterprise data and AI software platforms to governments and commercial organizations, generating revenue through multi-year software contracts, subscriptions, and implementation services, primarily via its Gotham (government) and Foundry (commercial) platforms, enhanced by its AI platform (AIP).$F$,
  'High', 'Strong',
  $F$Replacing Palantir's software is extremely complex due to deep operational integration, creating high switching costs, reinforced by long-term government relationships.$F$,
  'Niche',
  10, 8,
  230.43, 120.48, 236.26, $F$Snowflake, Databricks, Microsoft$F$, 'High Premium',
  '0.13', '21.80%', 3,
  'Strong uptrend', 'Neutral', 4,
  'Long', 130.00, 197.00, 96.00, 0,
  2.00, 4,
  26, 7, '2026-04-05 21:14:00+00'
)
ON CONFLICT (trading_id) DO UPDATE SET
  company_name = EXCLUDED.company_name, status = EXCLUDED.status, ticker = EXCLUDED.ticker,
  date_of_case = EXCLUDED.date_of_case, sector = EXCLUDED.sector,
  country_of_incorporation = EXCLUDED.country_of_incorporation,
  current_price_at_case = EXCLUDED.current_price_at_case,
  event_summary = EXCLUDED.event_summary, event_type = EXCLUDED.event_type,
  event_classification = EXCLUDED.event_classification, impact_of_news = EXCLUDED.impact_of_news,
  initial_market_assessment = EXCLUDED.initial_market_assessment,
  catalyst_1 = EXCLUDED.catalyst_1, catalyst_2 = EXCLUDED.catalyst_2,
  trigger_score = EXCLUDED.trigger_score, risk_1 = EXCLUDED.risk_1,
  business_model_explanation = EXCLUDED.business_model_explanation,
  earnings_quality = EXCLUDED.earnings_quality, competitive_advantage = EXCLUDED.competitive_advantage,
  competitive_advantage_defined = EXCLUDED.competitive_advantage_defined,
  market_position = EXCLUDED.market_position,
  esg_governance_quality_score = EXCLUDED.esg_governance_quality_score,
  fundamental_score = EXCLUDED.fundamental_score,
  current_pe = EXCLUDED.current_pe, forward_pe = EXCLUDED.forward_pe, ev_ebitda = EXCLUDED.ev_ebitda,
  top_3_competitors = EXCLUDED.top_3_competitors,
  prior_valuation_assessment = EXCLUDED.prior_valuation_assessment,
  eps = EXCLUDED.eps, operating_margin = EXCLUDED.operating_margin,
  valuation_score = EXCLUDED.valuation_score,
  primary_trend = EXCLUDED.primary_trend, overall_chart_assessment = EXCLUDED.overall_chart_assessment,
  technical_score = EXCLUDED.technical_score,
  direction = EXCLUDED.direction, entry_price_target = EXCLUDED.entry_price_target,
  take_profit = EXCLUDED.take_profit, stop_loss = EXCLUDED.stop_loss, leverage = EXCLUDED.leverage,
  risk_reward_ratio = EXCLUDED.risk_reward_ratio,
  expected_holding_period_months = EXCLUDED.expected_holding_period_months,
  total_score = EXCLUDED.total_score, confidence_score = EXCLUDED.confidence_score,
  created_at = EXCLUDED.created_at;


-- 3. Palo Alto (PANW-160-0326)
INSERT INTO public.cases (
  trading_id, company_name, status, ticker, date_of_case, sector, country_of_incorporation,
  current_price_at_case,
  event_summary, event_type, event_classification, impact_of_news, initial_market_assessment,
  catalyst_1, catalyst_2, trigger_score,
  risk_1,
  business_model_explanation, earnings_quality, competitive_advantage,
  competitive_advantage_defined, market_position,
  esg_governance_quality_score, fundamental_score,
  current_pe, forward_pe, ev_ebitda, top_3_competitors, prior_valuation_assessment,
  eps, operating_margin, valuation_score,
  primary_trend, overall_chart_assessment, technical_score,
  direction, entry_price_target, take_profit, stop_loss, leverage,
  risk_reward_ratio, expected_holding_period_months,
  total_score, confidence_score, created_at
) VALUES (
  'PANW-160-0326', $F$Palo Alto$F$, 'Active', 'PANW', '2026-03-11', 'Tech', 'US',
  164.00,
  $F$Costly acquisition of Chronosphere, declining margins, negative guidance update, fear of AI.$F$,
  $F$Guidance updates,Mergers & acquisitions (M&A),Sentiment risk$F$, 'Non-recurring', 'Uncertain', 'Unclear',
  $F$ Strong quarterly earnings + raised guidance on 19/3/2026$F$,
  $F$AI as a tailwind rather than a headwind$F$,
  4,
  $F$AI versnelt cyberdreigingen → hogere R&D kosten Microsoft geeft beveiliging gratis mee → prijsdruk CrowdStrike pakt marktaandeel → margecompressie$F$,
  $F$Palo Alto Networks is a leading cybersecurity company operating three core platforms: Strata, which covers traditional network security and next-generation firewalls; Prisma, which protects cloud infrastructure and remote access; and Cortex, an AI-driven platform for automated threat detection and response. The company serves 95% of the Fortune 100, making it the dominant player in enterprise cybersecurity.$F$,
  'High', 'Strong',
  $F$High switching costs$F$,
  'Leader',
  10, 9,
  91.99, 44.84, 59.09, $F$Crowdstrike, Fortninet, Check Point Software$F$, 'Fairly valued',
  '92.00', '15.00%', 5,
  'Uptrend', 'Slightly bullish', 3,
  'Long', 160.00, 215.00, 134.00, 0,
  2.00, 8,
  27, 7, '2026-04-05 21:14:00+00'
)
ON CONFLICT (trading_id) DO UPDATE SET
  company_name = EXCLUDED.company_name, status = EXCLUDED.status, ticker = EXCLUDED.ticker,
  date_of_case = EXCLUDED.date_of_case, sector = EXCLUDED.sector,
  country_of_incorporation = EXCLUDED.country_of_incorporation,
  current_price_at_case = EXCLUDED.current_price_at_case,
  event_summary = EXCLUDED.event_summary, event_type = EXCLUDED.event_type,
  event_classification = EXCLUDED.event_classification, impact_of_news = EXCLUDED.impact_of_news,
  initial_market_assessment = EXCLUDED.initial_market_assessment,
  catalyst_1 = EXCLUDED.catalyst_1, catalyst_2 = EXCLUDED.catalyst_2,
  trigger_score = EXCLUDED.trigger_score, risk_1 = EXCLUDED.risk_1,
  business_model_explanation = EXCLUDED.business_model_explanation,
  earnings_quality = EXCLUDED.earnings_quality, competitive_advantage = EXCLUDED.competitive_advantage,
  competitive_advantage_defined = EXCLUDED.competitive_advantage_defined,
  market_position = EXCLUDED.market_position,
  esg_governance_quality_score = EXCLUDED.esg_governance_quality_score,
  fundamental_score = EXCLUDED.fundamental_score,
  current_pe = EXCLUDED.current_pe, forward_pe = EXCLUDED.forward_pe, ev_ebitda = EXCLUDED.ev_ebitda,
  top_3_competitors = EXCLUDED.top_3_competitors,
  prior_valuation_assessment = EXCLUDED.prior_valuation_assessment,
  eps = EXCLUDED.eps, operating_margin = EXCLUDED.operating_margin,
  valuation_score = EXCLUDED.valuation_score,
  primary_trend = EXCLUDED.primary_trend, overall_chart_assessment = EXCLUDED.overall_chart_assessment,
  technical_score = EXCLUDED.technical_score,
  direction = EXCLUDED.direction, entry_price_target = EXCLUDED.entry_price_target,
  take_profit = EXCLUDED.take_profit, stop_loss = EXCLUDED.stop_loss, leverage = EXCLUDED.leverage,
  risk_reward_ratio = EXCLUDED.risk_reward_ratio,
  expected_holding_period_months = EXCLUDED.expected_holding_period_months,
  total_score = EXCLUDED.total_score, confidence_score = EXCLUDED.confidence_score,
  created_at = EXCLUDED.created_at;


-- 4. Oracle (ORCL-150-0326)
INSERT INTO public.cases (
  trading_id, company_name, status, ticker, date_of_case, sector, country_of_incorporation,
  current_price_at_case,
  event_summary, event_type, event_classification, impact_of_news, initial_market_assessment,
  catalyst_1, catalyst_2, trigger_score,
  risk_1,
  business_model_explanation, earnings_quality, competitive_advantage,
  competitive_advantage_defined, market_position,
  esg_governance_quality_score, net_debt_ebitda, fundamental_score,
  current_pe, forward_pe, ev_ebitda, top_3_competitors, prior_valuation_assessment,
  eps, operating_margin, valuation_score,
  primary_trend, overall_chart_assessment, technical_score,
  direction, entry_price_target, take_profit, stop_loss, leverage,
  risk_reward_ratio, expected_holding_period_months,
  total_score, confidence_score, created_at
) VALUES (
  'ORCL-150-0326', $F$Oracle$F$, 'Active', 'ORCL', '2026-03-18', 'Tech', 'US',
  152.00,
  $F$In September 2025, Oracle signed a $300B deal with OpenAI to build AI data centers (+42% stock surge). The downside: $113B in debt + $248 miljard in leasecontracts and 90%+ of its backlog dependent on a single unprofitable customer: OpenAI. The DeepSeek shock (January 2026) amplified doubts about AI infrastructure demand. Result: ~50% stock decline.$F$,
  $F$Earnings,Guidance updates,Balance sheet updates$F$, 'Non-recurring', 'Temporary', 'Overreaction',
  $F$High-risk, high-reward infrastructure bet on AI dominance$F$,
  $F$backed by a $523B contracted backlog$F$,
  6,
  $F$Oracle has bet everything on a single scenario that won't start paying off until 2027, financed with debt, dependent on one unprofitable customer, in a market where they have historically been a marginal player.$F$,
  $F$Oracle is a technology company that leads the database market (30% market share), offers enterprise software, and is undergoing a historic transformation into an AI datacenter provider. Through the $300B Stargate deal, it has become OpenAI's primary infrastructure supplier — with massive upside potential but dangerous customer concentration risk$F$,
  'High', 'Moderate',
  $F$Database lock-in, integrated ecosystem (cloud + database + enterprise software), faster/cheaper AI infrastructure than competitors, and political protection via Stargate$F$,
  'Leader',
  10, '4.00', 6,
  27.77, 19.34, 18.42, $F$Microsoft, AWS, SAP$F$, 'Fairly valued',
  '5.69', '32.68%', 6,
  'Uptrend', 'Slightly bullish', 3,
  'Long', 150.00, 306.00, 92.00, 0,
  2.50, 12,
  27, 7, '2026-04-05 21:14:00+00'
)
ON CONFLICT (trading_id) DO UPDATE SET
  company_name = EXCLUDED.company_name, status = EXCLUDED.status, ticker = EXCLUDED.ticker,
  date_of_case = EXCLUDED.date_of_case, sector = EXCLUDED.sector,
  country_of_incorporation = EXCLUDED.country_of_incorporation,
  current_price_at_case = EXCLUDED.current_price_at_case,
  event_summary = EXCLUDED.event_summary, event_type = EXCLUDED.event_type,
  event_classification = EXCLUDED.event_classification, impact_of_news = EXCLUDED.impact_of_news,
  initial_market_assessment = EXCLUDED.initial_market_assessment,
  catalyst_1 = EXCLUDED.catalyst_1, catalyst_2 = EXCLUDED.catalyst_2,
  trigger_score = EXCLUDED.trigger_score, risk_1 = EXCLUDED.risk_1,
  business_model_explanation = EXCLUDED.business_model_explanation,
  earnings_quality = EXCLUDED.earnings_quality, competitive_advantage = EXCLUDED.competitive_advantage,
  competitive_advantage_defined = EXCLUDED.competitive_advantage_defined,
  market_position = EXCLUDED.market_position,
  esg_governance_quality_score = EXCLUDED.esg_governance_quality_score,
  net_debt_ebitda = EXCLUDED.net_debt_ebitda,
  fundamental_score = EXCLUDED.fundamental_score,
  current_pe = EXCLUDED.current_pe, forward_pe = EXCLUDED.forward_pe, ev_ebitda = EXCLUDED.ev_ebitda,
  top_3_competitors = EXCLUDED.top_3_competitors,
  prior_valuation_assessment = EXCLUDED.prior_valuation_assessment,
  eps = EXCLUDED.eps, operating_margin = EXCLUDED.operating_margin,
  valuation_score = EXCLUDED.valuation_score,
  primary_trend = EXCLUDED.primary_trend, overall_chart_assessment = EXCLUDED.overall_chart_assessment,
  technical_score = EXCLUDED.technical_score,
  direction = EXCLUDED.direction, entry_price_target = EXCLUDED.entry_price_target,
  take_profit = EXCLUDED.take_profit, stop_loss = EXCLUDED.stop_loss, leverage = EXCLUDED.leverage,
  risk_reward_ratio = EXCLUDED.risk_reward_ratio,
  expected_holding_period_months = EXCLUDED.expected_holding_period_months,
  total_score = EXCLUDED.total_score, confidence_score = EXCLUDED.confidence_score,
  created_at = EXCLUDED.created_at;


-- 5. IBM (IBM-236-0326)
INSERT INTO public.cases (
  trading_id, company_name, status, ticker, date_of_case, sector, country_of_incorporation,
  current_price_at_case,
  event_summary, event_type, event_classification, impact_of_news, initial_market_assessment,
  catalyst_1, catalyst_2, trigger_score,
  risk_1,
  business_model_explanation, earnings_quality, competitive_advantage,
  competitive_advantage_defined, market_position,
  esg_governance_quality_score, net_debt_ebitda, fundamental_score,
  current_pe, forward_pe, ev_ebitda, top_3_competitors, prior_valuation_assessment,
  eps, operating_margin, valuation_score,
  primary_trend, overall_chart_assessment, technical_score,
  direction, entry_price_target, take_profit, stop_loss, leverage,
  risk_reward_ratio, expected_holding_period_months,
  total_score, confidence_score, created_at
) VALUES (
  'IBM-236-0326', $F$International Business Machines$F$, 'Active', 'IBM', '2026-03-25', 'Tech', 'US',
  240.00,
  $F$In February 2026, Anthropic announced that Claude Code could automate COBOL modernization — the conversion of legacy banking and government systems to modern programming languages. This directly threatened IBM Consulting's most lucrative work, causing a 13% single-day stock drop, IBM's worst in 25 years.$F$,
  'Competitive threat', 'Recurring', 'Structural', 'Justified',
  $F$Main catalyst: IBM's ongoing transformation from a consulting/hardware company into a high-margin software and AI business — driven by Red Hat and watsonx — positions it to grow recurring revenue$F$,
  $F$IBM's acquisition of Confluent for $11 billion expands its data infrastructure capabilities, strengthening its hybrid cloud and AI platform — confirming the strategic shift toward high-margin software is accelerating.$F$,
  5,
  $F$IBM's consulting segment faces structural pressure from AI automation and low-cost competitors, while its core markets are dominated by better-capitalized rivals like Microsoft and AWS. High debt ($61 billion) and a governance risk score of 7/10 add further concern.$F$,
  $F$IBM is an enterprise technology company that pivoted from a hardware-focused generalist to a high-margin software and AI company following the acquisition of Red Hat (2019) and the spin-off of Kyndryl (2021). Today it operates across three segments: Software (44% of revenue, 83.5% gross margin), Consulting (31%), and Infrastructure/hardware (23%). Its core offerings include hybrid cloud platforms (Red Hat OpenShift), AI software (watsonx), and automation tools, serving large enterprises and governments through recurring subscription revenue.$F$,
  'High', 'Strong',
  $F$IBM's core competitive advantage lies in its deep entrenchment within large enterprises and governments through high switching costs — particularly its mainframe monopoly and mission-critical software. Red Hat's open-source neutrality positions IBM as the only truly vendor-agnostic hybrid cloud platform, while decades of enterprise relationships provide a natural distribution channel for its expanding AI and automation software portfolio.$F$,
  'Top 3',
  7, '23.00', 7,
  21.70, 19.53, 16.03, $F$Microsoft (hybride cloud/AI), Accenture (consulting), Oracle (enterprise software)$F$, 'Fairly valued',
  '11.14', '24.77%', 6,
  'Uptrend', 'Neutral', 2,
  'Long', 236.00, 308.00, 208.00, 0,
  2.50, 6,
  26, 5, '2026-04-05 21:14:00+00'
)
ON CONFLICT (trading_id) DO UPDATE SET
  company_name = EXCLUDED.company_name, status = EXCLUDED.status, ticker = EXCLUDED.ticker,
  date_of_case = EXCLUDED.date_of_case, sector = EXCLUDED.sector,
  country_of_incorporation = EXCLUDED.country_of_incorporation,
  current_price_at_case = EXCLUDED.current_price_at_case,
  event_summary = EXCLUDED.event_summary, event_type = EXCLUDED.event_type,
  event_classification = EXCLUDED.event_classification, impact_of_news = EXCLUDED.impact_of_news,
  initial_market_assessment = EXCLUDED.initial_market_assessment,
  catalyst_1 = EXCLUDED.catalyst_1, catalyst_2 = EXCLUDED.catalyst_2,
  trigger_score = EXCLUDED.trigger_score, risk_1 = EXCLUDED.risk_1,
  business_model_explanation = EXCLUDED.business_model_explanation,
  earnings_quality = EXCLUDED.earnings_quality, competitive_advantage = EXCLUDED.competitive_advantage,
  competitive_advantage_defined = EXCLUDED.competitive_advantage_defined,
  market_position = EXCLUDED.market_position,
  esg_governance_quality_score = EXCLUDED.esg_governance_quality_score,
  net_debt_ebitda = EXCLUDED.net_debt_ebitda,
  fundamental_score = EXCLUDED.fundamental_score,
  current_pe = EXCLUDED.current_pe, forward_pe = EXCLUDED.forward_pe, ev_ebitda = EXCLUDED.ev_ebitda,
  top_3_competitors = EXCLUDED.top_3_competitors,
  prior_valuation_assessment = EXCLUDED.prior_valuation_assessment,
  eps = EXCLUDED.eps, operating_margin = EXCLUDED.operating_margin,
  valuation_score = EXCLUDED.valuation_score,
  primary_trend = EXCLUDED.primary_trend, overall_chart_assessment = EXCLUDED.overall_chart_assessment,
  technical_score = EXCLUDED.technical_score,
  direction = EXCLUDED.direction, entry_price_target = EXCLUDED.entry_price_target,
  take_profit = EXCLUDED.take_profit, stop_loss = EXCLUDED.stop_loss, leverage = EXCLUDED.leverage,
  risk_reward_ratio = EXCLUDED.risk_reward_ratio,
  expected_holding_period_months = EXCLUDED.expected_holding_period_months,
  total_score = EXCLUDED.total_score, confidence_score = EXCLUDED.confidence_score,
  created_at = EXCLUDED.created_at;


-- 6. Rheinmetall (RHM-1450-0426)
INSERT INTO public.cases (
  trading_id, company_name, status, ticker, date_of_case, sector, country_of_incorporation,
  current_price_at_case,
  event_summary, event_type, event_classification, impact_of_news, initial_market_assessment,
  catalyst_1, catalyst_2, trigger_score,
  risk_1,
  business_model_explanation, earnings_quality, competitive_advantage,
  competitive_advantage_defined, market_position,
  esg_governance_quality_score, net_debt_ebitda, fundamental_score,
  current_pe, forward_pe, ev_ebitda, top_3_competitors, prior_valuation_assessment,
  eps, operating_margin, valuation_score,
  primary_trend, overall_chart_assessment, technical_score,
  direction, entry_price_target, take_profit, stop_loss, leverage,
  risk_reward_ratio, expected_holding_period_months,
  total_score, confidence_score, created_at
) VALUES (
  'RHM-1450-0426', $F$Rheinmetall AG$F$, 'Active', 'RHM', '2026-04-01', 'Defense', 'DE',
  155.00,
  $F$Record FY2025 results (revenue €9.9B, +29%), but stock dropped ~25% from January highs driven by a 2026 guidance miss on free cash flow conversion (>40% vs. 70-90% expected) and margin (19% vs. 19.6%).$F$,
  'Guidance updates', 'Non-recurring', 'Temporary', 'Justified',
  $F$Structural demand ,German defense budget doubling toward 2029 (2% → 3.5% GDP)$F$,
  $F$Record order backlog €63.8B → expected €135B end 2026, Naval expansion (NVL/Blohm+Voss acquisition)$F$,
  6,
  $F$Rheinmetall trades at a premium valuation with limited margin for error, while facing execution risk on its record backlog, high capex weighing on free cash flow, and concentration risk with 38% of revenue from Germany — with a potential Ukraine ceasefire as a key demand-side risk.$F$,
  $F$Rheinmetall is a German defense company that develops and sells advanced defense technology. Its main segments are Vehicle Systems (50%), Weapons & Ammunition (36%), and Electronic Solutions (14%), with Naval Systems added from 2026 onwards.$F$,
  'Moderate', 'Moderate',
  $F$Pure-play land defense company with vertical integration across vehicles, ammunition, and electronics, focused on the European rearmament cycle.$F$,
  'Top 3',
  5, '2.00', 7,
  70.95, 44.84, 33.24, $F$BAE Systems, Saab, Leonardo$F$, 'High Premium',
  '17.46', '17.13%', 3,
  'Strong uptrend', 'Bullish', 4,
  'Long', 1450.00, 2350.00, 1150.00, 0,
  3.00, 5,
  26, 8, '2026-04-05 21:14:00+00'
)
ON CONFLICT (trading_id) DO UPDATE SET
  company_name = EXCLUDED.company_name, status = EXCLUDED.status, ticker = EXCLUDED.ticker,
  date_of_case = EXCLUDED.date_of_case, sector = EXCLUDED.sector,
  country_of_incorporation = EXCLUDED.country_of_incorporation,
  current_price_at_case = EXCLUDED.current_price_at_case,
  event_summary = EXCLUDED.event_summary, event_type = EXCLUDED.event_type,
  event_classification = EXCLUDED.event_classification, impact_of_news = EXCLUDED.impact_of_news,
  initial_market_assessment = EXCLUDED.initial_market_assessment,
  catalyst_1 = EXCLUDED.catalyst_1, catalyst_2 = EXCLUDED.catalyst_2,
  trigger_score = EXCLUDED.trigger_score, risk_1 = EXCLUDED.risk_1,
  business_model_explanation = EXCLUDED.business_model_explanation,
  earnings_quality = EXCLUDED.earnings_quality, competitive_advantage = EXCLUDED.competitive_advantage,
  competitive_advantage_defined = EXCLUDED.competitive_advantage_defined,
  market_position = EXCLUDED.market_position,
  esg_governance_quality_score = EXCLUDED.esg_governance_quality_score,
  net_debt_ebitda = EXCLUDED.net_debt_ebitda,
  fundamental_score = EXCLUDED.fundamental_score,
  current_pe = EXCLUDED.current_pe, forward_pe = EXCLUDED.forward_pe, ev_ebitda = EXCLUDED.ev_ebitda,
  top_3_competitors = EXCLUDED.top_3_competitors,
  prior_valuation_assessment = EXCLUDED.prior_valuation_assessment,
  eps = EXCLUDED.eps, operating_margin = EXCLUDED.operating_margin,
  valuation_score = EXCLUDED.valuation_score,
  primary_trend = EXCLUDED.primary_trend, overall_chart_assessment = EXCLUDED.overall_chart_assessment,
  technical_score = EXCLUDED.technical_score,
  direction = EXCLUDED.direction, entry_price_target = EXCLUDED.entry_price_target,
  take_profit = EXCLUDED.take_profit, stop_loss = EXCLUDED.stop_loss, leverage = EXCLUDED.leverage,
  risk_reward_ratio = EXCLUDED.risk_reward_ratio,
  expected_holding_period_months = EXCLUDED.expected_holding_period_months,
  total_score = EXCLUDED.total_score, confidence_score = EXCLUDED.confidence_score,
  created_at = EXCLUDED.created_at;


-- 7. Eli Lilly (LLY-886-0426)
INSERT INTO public.cases (
  trading_id, company_name, status, ticker, date_of_case, sector, industry, country_of_incorporation,
  current_price_at_case, week_52_high, week_52_low, analyst_1y_price_target,
  event_summary, event_type, event_classification, impact_of_news, initial_market_assessment,
  catalyst_1, catalyst_2, catalyst_3, catalyst_4, trigger_score,
  risk_1, risk_2, risk_3, risk_4,
  business_model_explanation, key_products_services, business_model_outlook,
  earnings_quality, competitive_advantage, competitive_advantage_defined, market_position,
  esg_governance_quality_score, esg_governance_explanation,
  net_debt_ebitda, fundamental_score,
  current_pe, forward_pe, ev_ebitda, current_vs_historical_multiples,
  top_3_competitors, prior_valuation_assessment,
  eps, operating_margin, layered_fcf_ttm, valuation_score,
  primary_trend, overall_chart_assessment, tradingview_ta_score, technical_score,
  direction, entry_price_target, take_profit, stop_loss, leverage,
  risk_reward_ratio, expected_holding_period_months,
  total_score, confidence_score, execute, created_at
) VALUES (
  'LLY-886-0426', $F$Eli Lilly$F$, 'Active', 'LLY', '2026-04-08', 'Health Care', 'Drug Manufactures', 'US',
  950.00, 1335.00, 625.00, 1209.00,
  $F$In early 2026, Lilly released its 2026 guidance which disappointed Wall Street as insufficiently ambitious, combined with pricing pressure from Trump's pharmaceutical tariff threats — leading to a ~15% drop from the ATH.$F$,
  'Guidance updates', 'Non-recurring', 'Temporary', 'Justified',
  $F$Kisunla (Alzheimer)
The only Alzheimer's treatment that stops once brain plaques are cleared — a unique differentiator in a largely untreated, massive market.$F$,
  $F$Tirzepatide Franchise
Two blockbusters — Mounjaro (diabetes) and Zepbound (obesity) — projected to reach $40 billion in combined annual sales, with Foundayo, the oral pill variant, now approved and opening an entirely new patient segment.$F$,
  $F$Deep Pipeline
36 active Phase 3 programs across oncology, immunology, neuroscience and metabolic disease — significantly reducing dependence on any single product.$F$,
  $F$Manufacturing Moat
Through a $55 billion investment, Lilly has built production capacity no competitor can match — creating a structural barrier that would take rivals a decade to replicate.$F$,
  4,
  $F$High Valuation
With a trailing P/E of 53, Lilly is priced for near-perfect execution. Any disappointment in revenue growth or pipeline results could trigger a significant correction$F$,
  $F$ISS Governance Score: 8
Lilly scores poorly on shareholder rights, audit transparency, and compensation policy. Ongoing lawsuits over insulin pricing and the absence of a clawback policy represent reputational and financial risks.$F$,
  $F$Political Pressure
The Trump administration's pharmaceutical tariffs and Medicare price negotiation policies directly threaten Lilly's pricing power. With 67% of revenue coming from the U.S., Lilly has significant exposure to domestic policy changes.$F$,
  $F$Concentration Risk
Approximately 75% of Lilly's revenue depends on a single molecule — tirzepatide (Mounjaro/Zepbound).$F$,
  $F$Eli Lilly and Company, founded in 1876, is a global pharmaceutical leader focused on the development, manufacturing, and commercialization of prescription medicines for human use. The company operates across 90 countries, with the United States representing its primary market (~67% of revenue), followed by Europe (~18%). Eli Lilly's portfolio is concentrated in high-growth therapeutic areas including diabetes, oncology, immunology, and neuroscience$F$,
  $F$Eli Lilly develops medicines through three clinical trial phases: Phase 1 (safety), Phase 2 (efficacy) and Phase 3 (large-scale validation). The odds of FDA approval from discovery are roughly 1 in 10,000, with R&D costs ranging from $500M to $2B per medicine. A blockbuster — over $1B in annual revenue — occurs in approximately 1 in 50,000 compounds. Once approved, patents provide up to 20 years of protection with gross margins around 80%.
Revenue is split across five segments: Diabetes & Obesity (incretins) 56%, Oncology 11%, Immunology 11%, Neuroscience 3%, and other 4%.$F$,
  'Strong', 'High', 'Strong',
  $F$1. Manufacturing Moat
Through a $55 billion investment, Lilly has built the largest GLP-1 production capacity in the world — a barrier competitors would need a decade to replicate.
2. Superior Drug Efficacy
Mounjaro (diabetes) and Zepbound (obesity) activate two hormone receptors simultaneously (GIP + GLP-1), outperforming single-receptor competitors like Ozempic. Foundayo, their newly approved once-daily pill, further expands the market by removing the injection barrier.
3. LillyDirect Platform
A direct-to-consumer channel that bypasses pharmacies and insurers, resulting in higher margins and a direct patient relationship. Foundayo is available for as little as $25/month.$F$,
  'Leader',
  8, $F$Shareholder Rights: 9 — Lilly has structural provisions that make it difficult for shareholders to vote out directors or influence policy. This is common among large U.S. pharmaceutical companies.
Audit: 8 — There are ongoing lawsuits against the three largest insulin producers, including Lilly, for allegedly keeping insulin prices artificially high in the U.S. for over 20 years.
Board & Compensation: 6 — Lilly currently lacks a formal clawback policy, meaning executive bonuses cannot be reclaimed in cases of misconduct or financial restatement. Shareholders have actively pushed for reform here.$F$,
  '1.17', 9,
  40.65, 27.47, 27.48, 'Below',
  $F$Novo Nordisk, AstraZeneca, Johnson&Johnson$F$, 'High Premium',
  '23.45', '31.67%', '$1.95', 3,
  'Strong uptrend', 'Bullish', 'Buy', 4,
  'Long', 886.00, 1370.00, 645.00, 0,
  2.00, 8,
  26, 8, true, '2026-04-09 11:44:00+00'
)
ON CONFLICT (trading_id) DO UPDATE SET
  company_name = EXCLUDED.company_name, status = EXCLUDED.status, ticker = EXCLUDED.ticker,
  date_of_case = EXCLUDED.date_of_case, sector = EXCLUDED.sector, industry = EXCLUDED.industry,
  country_of_incorporation = EXCLUDED.country_of_incorporation,
  current_price_at_case = EXCLUDED.current_price_at_case,
  week_52_high = EXCLUDED.week_52_high, week_52_low = EXCLUDED.week_52_low,
  analyst_1y_price_target = EXCLUDED.analyst_1y_price_target,
  event_summary = EXCLUDED.event_summary, event_type = EXCLUDED.event_type,
  event_classification = EXCLUDED.event_classification, impact_of_news = EXCLUDED.impact_of_news,
  initial_market_assessment = EXCLUDED.initial_market_assessment,
  catalyst_1 = EXCLUDED.catalyst_1, catalyst_2 = EXCLUDED.catalyst_2,
  catalyst_3 = EXCLUDED.catalyst_3, catalyst_4 = EXCLUDED.catalyst_4,
  trigger_score = EXCLUDED.trigger_score,
  risk_1 = EXCLUDED.risk_1, risk_2 = EXCLUDED.risk_2,
  risk_3 = EXCLUDED.risk_3, risk_4 = EXCLUDED.risk_4,
  business_model_explanation = EXCLUDED.business_model_explanation,
  key_products_services = EXCLUDED.key_products_services,
  business_model_outlook = EXCLUDED.business_model_outlook,
  earnings_quality = EXCLUDED.earnings_quality, competitive_advantage = EXCLUDED.competitive_advantage,
  competitive_advantage_defined = EXCLUDED.competitive_advantage_defined,
  market_position = EXCLUDED.market_position,
  esg_governance_quality_score = EXCLUDED.esg_governance_quality_score,
  esg_governance_explanation = EXCLUDED.esg_governance_explanation,
  net_debt_ebitda = EXCLUDED.net_debt_ebitda,
  fundamental_score = EXCLUDED.fundamental_score,
  current_pe = EXCLUDED.current_pe, forward_pe = EXCLUDED.forward_pe, ev_ebitda = EXCLUDED.ev_ebitda,
  current_vs_historical_multiples = EXCLUDED.current_vs_historical_multiples,
  top_3_competitors = EXCLUDED.top_3_competitors,
  prior_valuation_assessment = EXCLUDED.prior_valuation_assessment,
  eps = EXCLUDED.eps, operating_margin = EXCLUDED.operating_margin,
  layered_fcf_ttm = EXCLUDED.layered_fcf_ttm,
  valuation_score = EXCLUDED.valuation_score,
  primary_trend = EXCLUDED.primary_trend, overall_chart_assessment = EXCLUDED.overall_chart_assessment,
  tradingview_ta_score = EXCLUDED.tradingview_ta_score,
  technical_score = EXCLUDED.technical_score,
  direction = EXCLUDED.direction, entry_price_target = EXCLUDED.entry_price_target,
  take_profit = EXCLUDED.take_profit, stop_loss = EXCLUDED.stop_loss, leverage = EXCLUDED.leverage,
  risk_reward_ratio = EXCLUDED.risk_reward_ratio,
  expected_holding_period_months = EXCLUDED.expected_holding_period_months,
  total_score = EXCLUDED.total_score, confidence_score = EXCLUDED.confidence_score,
  execute = EXCLUDED.execute, created_at = EXCLUDED.created_at;


-- 8. Tesla (TSLA-303-0426) — Not Active
INSERT INTO public.cases (
  trading_id, company_name, status, ticker, date_of_case, sector, industry, country_of_incorporation,
  current_price_at_case, week_52_high, week_52_low, analyst_1y_price_target,
  event_summary, event_type, event_classification, impact_of_news, initial_market_assessment,
  catalyst_1, catalyst_2, catalyst_3, catalyst_4, trigger_score,
  risk_1, risk_2, risk_3, risk_4,
  business_model_explanation, key_products_services, business_model_outlook,
  earnings_quality, competitive_advantage, competitive_advantage_defined, market_position,
  esg_governance_quality_score, esg_governance_explanation,
  net_debt_ebitda, fundamental_score,
  current_pe, forward_pe, ev_ebitda, current_vs_historical_multiples,
  top_3_competitors, prior_valuation_assessment,
  eps, operating_margin, layered_fcf_ttm, valuation_score,
  primary_trend, overall_chart_assessment, tradingview_ta_score, technical_score,
  direction, entry_price_target, take_profit, stop_loss, leverage,
  risk_reward_ratio, expected_holding_period_months,
  total_score, confidence_score, execute, created_at, conviction_score
) VALUES (
  'TSLA-303-0426', $F$Tesla$F$, 'Not Active', 'TSLA', '2026-04-16', 'Consumer Cyclical', 'Auto Manufacturer', 'US',
  390.00, 498.00, 223.00, 414.59,
  $F$Tesla's stock has declined roughly 30% year-to-date, driven by its largest annual delivery decline in history (−8.5% in 2025) and accelerating market share losses to lower-cost rivals like BYD in Europe and China. Also the stock trades at ~358x earnings.$F$,
  $F$Earnings,Competitive threat,sentiment-driven sell-off$F$, 'Non-recurring', 'Uncertain', 'Justified',
  $F$FSD & Autonomous Driving Leadership
Tesla leads the autonomous driving space with 7+ billion real-world miles of training data — a dataset no competitor can replicate. FSD v14 is live in the US and China, with EU-wide approval potentially unlocking a major new market in H2 2026.$F$,
  $F$Cybercab & Optimus
Production of the Cybercab robotaxi started April 2026, with commercial launch targeted for late 2026. If successful, it transforms Tesla's revenue model from one-time vehicle sales to recurring mobility income. Optimus, targeting 2027, represents an entirely new addressable market in humanoid robotics.$F$,
  $F$Energy Storage Growth
The Energy segment is Tesla's fastest-growing and highest-margin business (30% gross margin), driven by Megapack deployments to utilities and data centers — pure B2B. A third Megafactory opens in Houston in 2026, with deployments up 49% YoY in 2025.$F$,
  $F$AI5 Chip
Tesla's custom AI5 chip taped out April 2026, delivering 40-50x performance improvement over AI4. This reduces dependency on Nvidia, lowers AI infrastructure costs, and accelerates FSD and Cybercab capabilities significantly.$F$,
  4,
  $F$Extreme Overvaluation.
Tesla trades at ~100x forward earnings, a premium that fully prices in the success of Cybercab, Optimus, and FSD. If any of these future platforms disappoint or face delays, the stock has significant downside with no fundamental floor from its core automotive business.$F$,
  $F$Chinese Competition
BYD has overtaken Tesla as the world's largest EV seller, holding ~19% global BEV market share versus Tesla's ~9%. Chinese manufacturers compete at price points Tesla cannot match, and are rapidly expanding into Europe and other key markets.$F$,
  $F$Regulatory Credit Collapse
Regulatory credits contributed ~16% of automotive gross profit in 2025 ($2.0B revenue at near-100% margin). The Trump administration's removal of CAFE penalty enforcement eliminates the incentive for competitors to purchase these credits, with revenue projected to near zero by 2027.$F$,
  $F$Execution Risk and Management Distraction
Musk simultaneously runs Tesla, SpaceX, xAI, X, and DOGE. Tesla's history of missed timelines — robotaxi promised since 2019, AI5 delayed two years — raises serious questions about whether the future platforms underpinning the current valuation will deliver on schedule, if at all.$F$,
  $F$Tesla is a vertically integrated electric vehicle and clean energy company with ~50% of revenue from the US, 22% from China, and 28% from the rest of the world. Beyond vehicle sales, Tesla generates recurring revenue through FSD subscriptions, its Supercharger network, and insurance — treating each car as a long-term revenue platform. The company is actively transitioning from a pure-play automaker toward an AI-integrated technology platform, with growing exposure to energy storage, autonomous driving, and humanoid robotics.$F$,
  $F$Tesla operates across three segments: Automotive (73%, 18% gross margin), dominated by the Model 3 and Model Y at 97% of deliveries; Energy Generation & Storage (14%, 30% gross margin), covering Megapack batteries and solar, the fastest-growing and highest-margin segment; and Services & Other (13%, 7.4% gross margin), including Supercharging and insurance.
Beyond its core business, Tesla is investing in two future platforms: the Cybercab autonomous robotaxi (production started April 2026) and Optimus, a humanoid robot targeting 2027.$F$,
  'Strong', 'High', 'Moderate',
  $F$Tesla's main competitive advantages are its proprietary FSD software trained on 7+ billion real-world miles — a dataset no competitor can replicate quickly — its Supercharger network, now the North American standard, and its vertical integration across batteries, software, and AI silicon. Combined with a $44B cash position and a rapidly scaling energy storage business, Tesla is difficult to compete with on multiple fronts simultaneously.$F$,
  'Top 3',
  10, $F$Elon Musk is Tesla's largest individual shareholder, owning approximately 13-15% of outstanding shares directly, rising to ~25% when including exercisable options. He has publicly stated his desire to reach 25% voting control to strengthen his influence over Tesla's AI and robotics direction — a threshold he has not yet reached. This concentration of ownership is a key governance concern$F$,
  '-3.40', 8,
  356.32, 188.68, 122.53, 'Above',
  $F$BYD, Volkswagen Group, GM$F$, 'Premium',
  '1.10', '4.70%', '$3.73', 2,
  'Uptrend', 'Bullish', 'Buy', 3,
  'Long', 303.00, 590.00, 185.00, 0,
  2.50, 6,
  23, 5, true, '2026-04-16 14:19:00+00', 6
)
ON CONFLICT (trading_id) DO UPDATE SET
  company_name = EXCLUDED.company_name, status = EXCLUDED.status, ticker = EXCLUDED.ticker,
  date_of_case = EXCLUDED.date_of_case, sector = EXCLUDED.sector, industry = EXCLUDED.industry,
  country_of_incorporation = EXCLUDED.country_of_incorporation,
  current_price_at_case = EXCLUDED.current_price_at_case,
  week_52_high = EXCLUDED.week_52_high, week_52_low = EXCLUDED.week_52_low,
  analyst_1y_price_target = EXCLUDED.analyst_1y_price_target,
  event_summary = EXCLUDED.event_summary, event_type = EXCLUDED.event_type,
  event_classification = EXCLUDED.event_classification, impact_of_news = EXCLUDED.impact_of_news,
  initial_market_assessment = EXCLUDED.initial_market_assessment,
  catalyst_1 = EXCLUDED.catalyst_1, catalyst_2 = EXCLUDED.catalyst_2,
  catalyst_3 = EXCLUDED.catalyst_3, catalyst_4 = EXCLUDED.catalyst_4,
  trigger_score = EXCLUDED.trigger_score,
  risk_1 = EXCLUDED.risk_1, risk_2 = EXCLUDED.risk_2,
  risk_3 = EXCLUDED.risk_3, risk_4 = EXCLUDED.risk_4,
  business_model_explanation = EXCLUDED.business_model_explanation,
  key_products_services = EXCLUDED.key_products_services,
  business_model_outlook = EXCLUDED.business_model_outlook,
  earnings_quality = EXCLUDED.earnings_quality, competitive_advantage = EXCLUDED.competitive_advantage,
  competitive_advantage_defined = EXCLUDED.competitive_advantage_defined,
  market_position = EXCLUDED.market_position,
  esg_governance_quality_score = EXCLUDED.esg_governance_quality_score,
  esg_governance_explanation = EXCLUDED.esg_governance_explanation,
  net_debt_ebitda = EXCLUDED.net_debt_ebitda,
  fundamental_score = EXCLUDED.fundamental_score,
  current_pe = EXCLUDED.current_pe, forward_pe = EXCLUDED.forward_pe, ev_ebitda = EXCLUDED.ev_ebitda,
  current_vs_historical_multiples = EXCLUDED.current_vs_historical_multiples,
  top_3_competitors = EXCLUDED.top_3_competitors,
  prior_valuation_assessment = EXCLUDED.prior_valuation_assessment,
  eps = EXCLUDED.eps, operating_margin = EXCLUDED.operating_margin,
  layered_fcf_ttm = EXCLUDED.layered_fcf_ttm,
  valuation_score = EXCLUDED.valuation_score,
  primary_trend = EXCLUDED.primary_trend, overall_chart_assessment = EXCLUDED.overall_chart_assessment,
  tradingview_ta_score = EXCLUDED.tradingview_ta_score,
  technical_score = EXCLUDED.technical_score,
  direction = EXCLUDED.direction, entry_price_target = EXCLUDED.entry_price_target,
  take_profit = EXCLUDED.take_profit, stop_loss = EXCLUDED.stop_loss, leverage = EXCLUDED.leverage,
  risk_reward_ratio = EXCLUDED.risk_reward_ratio,
  expected_holding_period_months = EXCLUDED.expected_holding_period_months,
  total_score = EXCLUDED.total_score, confidence_score = EXCLUDED.confidence_score,
  execute = EXCLUDED.execute, created_at = EXCLUDED.created_at,
  conviction_score = EXCLUDED.conviction_score;


-- 9. Visa (V-305-0426)
INSERT INTO public.cases (
  trading_id, company_name, status, ticker, date_of_case, sector, industry, country_of_incorporation,
  current_price_at_case, week_52_high, week_52_low, analyst_1y_price_target,
  event_summary, event_type, event_classification, impact_of_news, initial_market_assessment,
  catalyst_1, catalyst_2, catalyst_3, catalyst_4, trigger_score,
  risk_1, risk_2, risk_3, risk_4,
  business_model_explanation, key_products_services, business_model_outlook,
  earnings_quality, competitive_advantage, competitive_advantage_defined, market_position,
  esg_governance_quality_score, net_debt_ebitda, fundamental_score,
  current_pe, forward_pe, ev_ebitda, current_vs_historical_multiples,
  top_3_competitors, prior_valuation_assessment,
  eps, operating_margin, layered_fcf_ttm, valuation_score,
  primary_trend, overall_chart_assessment, tradingview_ta_score, technical_score,
  direction, entry_price_target, take_profit, stop_loss, leverage,
  risk_reward_ratio, expected_holding_period_months,
  total_score, confidence_score, execute, created_at, conviction_score
) VALUES (
  'V-305-0426', $F$VISA$F$, 'Active', 'V', '2026-04-22', 'Financials', 'Transaction & Payment Processing Services', 'US',
  309.00, 375.00, 293.00, 393.43,
  $F$Visa has declined ~17% from its 52-week high due to three converging pressures: (1) macro uncertainty driven by Trump's 2025 tariff war, raising fears of slowing consumer spending and reduced payment volumes; (2) an ongoing DOJ antitrust lawsuit filed in 2024 alleging Visa illegally monopolizes the U.S. debit card network, creating regulatory overhang; and (3) a broader selloff in high-valuation growth equities amid the tariff-driven risk-off environment. None of these reflect a deterioration in Visa's underlying business fundamentals.$F$,
  'sentiment-driven sell-off', 'Non-recurring', 'Uncertain', 'Overreaction',
  $F$DOJ resolution — dismissal or settlement removes the largest regulatory overhang, enabling a re-rating toward historical multiples.$F$,
  $F$Cross-border volume growth — structural growth in global travel and e-commerce drives Visa's highest-margin segment.$F$,
  $F$Value-added services — Visa Direct, B2B payments, and tokenization are growing faster than the core business, expanding margins beyond pure transaction processing.$F$,
  $F$ RTP integration — Rather than competing with real-time payment networks, Visa is positioning itself as the value-added layer on top of them, offering fraud detection, tokenization, and global connectivity that RTP networks cannot provide — turning a structural threat into a growth opportunity.$F$,
  6,
  $F$DOJ antitrust lawsuit — a ruling against Visa could force the debit network open to competitors, materially impacting pricing power and volume.$F$,
  $F$Consumer spending slowdown — Visa's revenue is directly tied to payment volume; a tariff-driven recession would hit the top line immediately.$F$,
  $F$Real-time payment networks — bank-to-bank systems such as IDEAL, FedNow, UPI, and PIX structurally bypass VisaNet, representing a long-term disintermediation threat. (risk in 10-20 years)$F$,
  $F$Geopolitical risk — de-globalization and trade friction reduce cross-border transaction volume, Visa's highest-margin segment.$F$,
  $F$Founded in 1958 by Bank of America, Visa grew into a global payment network through a licensing model — allowing banks worldwide to issue Visa-branded cards, creating a self-reinforcing network effect where more banks meant more cardholders, which attracted more merchants, which attracted more banks. Today, Visa's network (VisaNet) sits in the middle of every transaction, routing authorization between the cardholder's bank and the merchant's bank in under 300 milliseconds. Visa collects a small fee on each transaction, carries zero credit risk, and processes up to 65,000 transactions per second — commanding ~60% of global card payment volume.$F$,
  $F$Visa operates four revenue segments: data processing (~38%, per-transaction fees on VisaNet), service revenues (~33%, volume-based fees on total payment volume), international transactions (~26%, cross-border fees with the highest margins), and other revenues (~5%, licensing, analytics, and value-added services). Client incentives (~25% of gross revenue) are rebates paid to issuing banks to secure volume commitments, recorded as contra-revenue.$F$,
  'Strong', 'High', 'Strong',
  $F$Visa's moat stems from an unrivaled two-sided network effect: 4.4 billion cards, 130+ million merchants, 200+ countries — decades in the making and virtually impossible to replicate. More cardholders attract more merchants, and vice versa. Deep bank integrations with VisaNet create massive switching costs, while 230 billion annual transactions generate scale advantages that compound over time.$F$,
  'Leader',
  2, '0.73', 9,
  2910.00, 25.00, 22.62, 'Below',
  $F$American Express, Mastercard, Paypal$F$, 'Fairly valued',
  '10.66', '68.30%', '$22.00', 7,
  'Uptrend', 'Slightly bullish', 'Sell', 3,
  'Long', 305.00, 395.00, 261.00, 0,
  2.00, 7,
  34, 9, true, '2026-04-22 20:37:00+00', 9
)
ON CONFLICT (trading_id) DO UPDATE SET
  company_name = EXCLUDED.company_name, status = EXCLUDED.status, ticker = EXCLUDED.ticker,
  date_of_case = EXCLUDED.date_of_case, sector = EXCLUDED.sector, industry = EXCLUDED.industry,
  country_of_incorporation = EXCLUDED.country_of_incorporation,
  current_price_at_case = EXCLUDED.current_price_at_case,
  week_52_high = EXCLUDED.week_52_high, week_52_low = EXCLUDED.week_52_low,
  analyst_1y_price_target = EXCLUDED.analyst_1y_price_target,
  event_summary = EXCLUDED.event_summary, event_type = EXCLUDED.event_type,
  event_classification = EXCLUDED.event_classification, impact_of_news = EXCLUDED.impact_of_news,
  initial_market_assessment = EXCLUDED.initial_market_assessment,
  catalyst_1 = EXCLUDED.catalyst_1, catalyst_2 = EXCLUDED.catalyst_2,
  catalyst_3 = EXCLUDED.catalyst_3, catalyst_4 = EXCLUDED.catalyst_4,
  trigger_score = EXCLUDED.trigger_score,
  risk_1 = EXCLUDED.risk_1, risk_2 = EXCLUDED.risk_2,
  risk_3 = EXCLUDED.risk_3, risk_4 = EXCLUDED.risk_4,
  business_model_explanation = EXCLUDED.business_model_explanation,
  key_products_services = EXCLUDED.key_products_services,
  business_model_outlook = EXCLUDED.business_model_outlook,
  earnings_quality = EXCLUDED.earnings_quality, competitive_advantage = EXCLUDED.competitive_advantage,
  competitive_advantage_defined = EXCLUDED.competitive_advantage_defined,
  market_position = EXCLUDED.market_position,
  esg_governance_quality_score = EXCLUDED.esg_governance_quality_score,
  net_debt_ebitda = EXCLUDED.net_debt_ebitda,
  fundamental_score = EXCLUDED.fundamental_score,
  current_pe = EXCLUDED.current_pe, forward_pe = EXCLUDED.forward_pe, ev_ebitda = EXCLUDED.ev_ebitda,
  current_vs_historical_multiples = EXCLUDED.current_vs_historical_multiples,
  top_3_competitors = EXCLUDED.top_3_competitors,
  prior_valuation_assessment = EXCLUDED.prior_valuation_assessment,
  eps = EXCLUDED.eps, operating_margin = EXCLUDED.operating_margin,
  layered_fcf_ttm = EXCLUDED.layered_fcf_ttm,
  valuation_score = EXCLUDED.valuation_score,
  primary_trend = EXCLUDED.primary_trend, overall_chart_assessment = EXCLUDED.overall_chart_assessment,
  tradingview_ta_score = EXCLUDED.tradingview_ta_score,
  technical_score = EXCLUDED.technical_score,
  direction = EXCLUDED.direction, entry_price_target = EXCLUDED.entry_price_target,
  take_profit = EXCLUDED.take_profit, stop_loss = EXCLUDED.stop_loss, leverage = EXCLUDED.leverage,
  risk_reward_ratio = EXCLUDED.risk_reward_ratio,
  expected_holding_period_months = EXCLUDED.expected_holding_period_months,
  total_score = EXCLUDED.total_score, confidence_score = EXCLUDED.confidence_score,
  execute = EXCLUDED.execute, created_at = EXCLUDED.created_at,
  conviction_score = EXCLUDED.conviction_score;


-- 10. Tencent (0700.HK-427-0426) — Not Active
INSERT INTO public.cases (
  trading_id, company_name, status, ticker, date_of_case, sector, industry, country_of_incorporation,
  current_price_at_case, week_52_high, week_52_low, analyst_1y_price_target,
  event_summary, event_type, event_classification, impact_of_news, initial_market_assessment,
  catalyst_1, catalyst_2, catalyst_3, catalyst_4, trigger_score,
  risk_1, risk_2, risk_3, risk_4,
  business_model_explanation, key_products_services, business_model_outlook,
  earnings_quality, competitive_advantage, competitive_advantage_defined, market_position,
  esg_governance_quality_score, esg_governance_explanation,
  net_debt_ebitda, fundamental_score,
  current_pe, forward_pe, ev_ebitda, current_vs_historical_multiples,
  top_3_competitors, prior_valuation_assessment,
  eps, operating_margin, layered_fcf_ttm, valuation_score,
  primary_trend, overall_chart_assessment, tradingview_ta_score, technical_score,
  direction, entry_price_target, take_profit, stop_loss, leverage,
  risk_reward_ratio, expected_holding_period_months,
  total_score, confidence_score, execute, created_at, conviction_score
) VALUES (
  '0700.HK-427-0426', $F$Tencent Holdings Limited$F$, 'Not Active', '0700.HK', '2026-04-29',
  'Communication Services', 'Internet Content & Information', 'China',
  479.00, 683.00, 472.00, 723.38,
  $F$In January 2025, the Pentagon added Tencent to its Chinese military company list, restricting U.S. investment and raising the stock's structural risk premium, compounded by market skepticism over whether Tencent's AI investments can translate into real competitive differentiation, with its Yuanbao assistant still significantly trailing ByteDance's Doubao in daily active users.$F$,
  'Valuation-driven correction', 'Recurring', 'Uncertain', 'Justified',
  $F$WeChat ad monetization re-rating
WeChat's ad ARPU is a fraction of Meta's despite comparable engagement. Any step-up in ad load or AI-driven targeting could trigger a significant earnings beat.$F$,
  $F$ International gaming acceleration
International games grew 43% YoY in Q3 2025. A strong pipeline from Riot, Supercell and new studios reduces China regulatory dependency in the revenue mix.$F$,
  $F$AI integration payoff
Evidence that Hunyuan and AI Marketing Plus are materially driving ad revenue or game development efficiency would shift the narrative from AI skeptic to AI winner.$F$,
  $F$Buyback + portfolio monetization
Continued buybacks mechanically boost EPS. Partial monetization of the ~$100B listed portfolio could unlock significant hidden value the market currently discounts.$F$,
  3,
  $F$Geopolitical escalation
Pentagon listing already restricts U.S. investment. Any escalation — broader sanctions or trade war intensification — shrinks the investor base and compresses multiples furthe$F$,
  $F$Chinese regulatory risk
Beijing can move overnight on gaming, payments, or data. Tencent is always the primary target given its dominance across China's digital infrastructure.$F$,
  $F$AI monetization lag
Yuanbao trails ByteDance's Doubao 2:1 in DAUs. If Tencent can't convert heavy AI capex into revenue, it becomes a drag and the market reprices.$F$,
  $F$Macro China weakness
Weak consumer spending and deflationary pressure directly hit ad budgets, gaming spend, and WeChat Pay volumes — all core revenue drivers.$F$,
  $F$Tencent is China's largest technology conglomerate, operating across gaming, social media, fintech, cloud, and digital content. Its superapp WeChat — with 1.3 billion users — serves as the primary distribution channel across all its businesses. Through wholly owned studios Riot Games and Supercell, Tencent is the world's largest gaming company by revenue. Beyond its core operations, approximately one-third of Tencent's total value sits in a ~$140 billion investment portfolio, holding strategic stakes in companies including Epic Games (40%), Meituan, JD.com, Spotify, and Sea Limited.$F$,
  $F$Tencent operates across three core revenue segments. Value-Added Services accounts for 50% of revenue, driven primarily by domestic and international gaming — including wholly owned studios Riot Games and Supercell — alongside social network subscriptions. FinTech & Business Services contributes 30%, through WeChat Pay, cloud infrastructure, and enterprise SaaS. Marketing Services makes up the remaining 19%, monetizing Tencent's 1.3 billion WeChat users through advertising across Moments, Official Accounts, and Mini Programs.
Beyond its core operations, Tencent holds a ~$140 billion investment portfolio diversified across gaming (40%), e-commerce (30%), fintech (12%), music and social media (15%). 70% from all revenue is direct/indirect because of WeChat. Users are on average 4 hours in Wechat per day.$F$,
  'Strong', 'High', 'Strong',
  $F$Tencent's moat is built on WeChat's unmatched network effects — with 1.3 billion users whose entire digital life, payments, work, and social connections run through a single app they simply cannot leave. This is reinforced by extreme switching costs, deep ecosystem lock-in through Mini Programs, an unrivaled gaming IP portfolio via Riot and Supercell, and the structural advantage of foreign competitors being blocked in China.$F$,
  'Leader',
  10, $F$Tencent scores a 10/10 (highest risk) on ISS Governance, driven primarily by its compensation practices — executive pay lacks transparency and is poorly linked to shareholder returns, with heavy equity grants and no clear performance requirements. Secondary concerns include limited shareholder rights via its VIE structure, which means foreign investors technically don't own the underlying Chinese operations directly, and moderate board independence issues typical of founder-led Chinese tech companies. The audit pillar (2/10) is the sole bright spot.$F$,
  '-0.33', 8,
  17.12, 13.62, 10.42, 'Below',
  $F$META, BABA, NTES$F$, 'Discounted',
  '27.67', '33.13%', '$139.39', 6,
  'Uptrend', 'Neutral', 'Sell', 3,
  'Long', 427.00, 792.00, 247.00, 0,
  2.00, 8,
  28, 8, true, '2026-04-29 23:36:00+00', 8
)
ON CONFLICT (trading_id) DO UPDATE SET
  company_name = EXCLUDED.company_name, status = EXCLUDED.status, ticker = EXCLUDED.ticker,
  date_of_case = EXCLUDED.date_of_case, sector = EXCLUDED.sector, industry = EXCLUDED.industry,
  country_of_incorporation = EXCLUDED.country_of_incorporation,
  current_price_at_case = EXCLUDED.current_price_at_case,
  week_52_high = EXCLUDED.week_52_high, week_52_low = EXCLUDED.week_52_low,
  analyst_1y_price_target = EXCLUDED.analyst_1y_price_target,
  event_summary = EXCLUDED.event_summary, event_type = EXCLUDED.event_type,
  event_classification = EXCLUDED.event_classification, impact_of_news = EXCLUDED.impact_of_news,
  initial_market_assessment = EXCLUDED.initial_market_assessment,
  catalyst_1 = EXCLUDED.catalyst_1, catalyst_2 = EXCLUDED.catalyst_2,
  catalyst_3 = EXCLUDED.catalyst_3, catalyst_4 = EXCLUDED.catalyst_4,
  trigger_score = EXCLUDED.trigger_score,
  risk_1 = EXCLUDED.risk_1, risk_2 = EXCLUDED.risk_2,
  risk_3 = EXCLUDED.risk_3, risk_4 = EXCLUDED.risk_4,
  business_model_explanation = EXCLUDED.business_model_explanation,
  key_products_services = EXCLUDED.key_products_services,
  business_model_outlook = EXCLUDED.business_model_outlook,
  earnings_quality = EXCLUDED.earnings_quality, competitive_advantage = EXCLUDED.competitive_advantage,
  competitive_advantage_defined = EXCLUDED.competitive_advantage_defined,
  market_position = EXCLUDED.market_position,
  esg_governance_quality_score = EXCLUDED.esg_governance_quality_score,
  esg_governance_explanation = EXCLUDED.esg_governance_explanation,
  net_debt_ebitda = EXCLUDED.net_debt_ebitda,
  fundamental_score = EXCLUDED.fundamental_score,
  current_pe = EXCLUDED.current_pe, forward_pe = EXCLUDED.forward_pe, ev_ebitda = EXCLUDED.ev_ebitda,
  current_vs_historical_multiples = EXCLUDED.current_vs_historical_multiples,
  top_3_competitors = EXCLUDED.top_3_competitors,
  prior_valuation_assessment = EXCLUDED.prior_valuation_assessment,
  eps = EXCLUDED.eps, operating_margin = EXCLUDED.operating_margin,
  layered_fcf_ttm = EXCLUDED.layered_fcf_ttm,
  valuation_score = EXCLUDED.valuation_score,
  primary_trend = EXCLUDED.primary_trend, overall_chart_assessment = EXCLUDED.overall_chart_assessment,
  tradingview_ta_score = EXCLUDED.tradingview_ta_score,
  technical_score = EXCLUDED.technical_score,
  direction = EXCLUDED.direction, entry_price_target = EXCLUDED.entry_price_target,
  take_profit = EXCLUDED.take_profit, stop_loss = EXCLUDED.stop_loss, leverage = EXCLUDED.leverage,
  risk_reward_ratio = EXCLUDED.risk_reward_ratio,
  expected_holding_period_months = EXCLUDED.expected_holding_period_months,
  total_score = EXCLUDED.total_score, confidence_score = EXCLUDED.confidence_score,
  execute = EXCLUDED.execute, created_at = EXCLUDED.created_at,
  conviction_score = EXCLUDED.conviction_score;


-- 11. SoftBank (9984.T-4400-0526) — Not Active
INSERT INTO public.cases (
  trading_id, company_name, status, ticker, date_of_case, sector, industry, country_of_incorporation,
  current_price_at_case, week_52_high, week_52_low, analyst_1y_price_target,
  event_summary, event_type, event_classification, impact_of_news, initial_market_assessment,
  catalyst_1, catalyst_2, catalyst_3, catalyst_4, trigger_score,
  risk_1, risk_2, risk_3, risk_4,
  business_model_explanation, key_products_services, business_model_outlook,
  earnings_quality, competitive_advantage, competitive_advantage_defined, market_position,
  esg_governance_quality_score, net_debt_ebitda, fundamental_score,
  current_pe, forward_pe, ev_ebitda, current_vs_historical_multiples,
  top_3_competitors, prior_valuation_assessment,
  eps, operating_margin, layered_fcf_ttm, valuation_score,
  primary_trend, overall_chart_assessment, tradingview_ta_score, technical_score,
  direction, entry_price_target, take_profit, stop_loss, leverage,
  risk_reward_ratio, expected_holding_period_months,
  total_score, confidence_score, why_not_executed, created_at, conviction_score
) VALUES (
  '9984.T-4400-0526', $F$SoftBank Group Corp.$F$, 'Not Active', '9984.T', '2026-05-05',
  'Communication Services', 'Telecom Services', 'Japan',
  5424.00, 6900.00, 1800.00, 5375.61,
  $F$SoftBank dropped ~10% on April 28, 2026, after the WSJ reported that OpenAI missed its internal revenue and user growth targets, with OpenAI's CFO reportedly nervous about Altman's compute spending. The selloff spread across the entire AI infrastructure trade — Oracle, Broadcom, AMD, CoreWeave all fell — but SoftBank was hit hardest as OpenAI's largest investor (~$34.7bn invested, ~11% stake). The market is increasingly scrutinizing AI monetization over hype, which is structurally problematic for SoftBank given that OpenAI represents ~15-20% of NAV and is the core thesis behind Stargate.$F$,
  'sentiment-driven sell-off', 'Recurring', 'Uncertain', 'Justified',
  $F$OpenAI IPO / valuation milestone — converts $34.7bn private stake to market-verified value; historically triggers NAV-discount compression (see ARM IPO 2023).$F$,
  $F$ARM revenue acceleration — AI datacenter royalty growth directly drives ~50% of NAV.$F$,
  $F$NAV-discount compression — trading at 30-40% discount; UBS targets 20%, Morgan Stanley 30%. Elliott pushing buybacks accelerates this.$F$,
  $F$PayPay Nasdaq IPO — first major Vision Fund 2 monetization; validates private portfolio and generates cash for redeployment.$F$,
  2,
  $F$OpenAI concentration — ~15-20% of NAV, private, not profitable. Any missed revenue target hits NAV directly, as seen April 2026.$F$,
  $F$ARM concentration — ~50% of NAV, with $8.5bn margin loan on top. A sustained ARM correction is existential.$F$,
  $F$Leverage & liquidity — LTV at ~19-20%, near 25% limit. Alibaba, Nvidia, T-Mobile largely sold. Limited buffer remaining.$F$,
  $F$Key-person risk — entire strategy is Son's AGI conviction. Track record inconsistent: Alibaba (brilliant), WeWork (disastrous), Nvidia (sold too early).$F$,
  $F$SoftBank Group is a Japanese tech conglomerate structured as a leveraged investment holding company. It operates through three components: a strategic holding arm (ARM ~90%, OpenAI ~11%, SoftBank Corp. ~40%), fund management (Vision Fund 1 at $100bn, Vision Fund 2, and LatAm Funds), and operational subsidiaries generating recurring revenue via SoftBank Corp. (Japanese telecom) and ARM Holdings (chip IP licensing).
In FY2025 SoftBank added an AI Computing segment (ARM, Ampere, Graphcore), reflecting a full strategic pivot toward AI — most visibly through Stargate, a $500bn AI datacenter JV with OpenAI and Oracle.
Son does not manage for earnings but targets NAV per share, funding bets through asset sales, margin loans, and debt — making SoftBank effectively a leveraged portfolio on AI valuations.$F$,
  $F$SoftBank's holding company solely allocates capital. Real recurring revenue comes from two segments: SoftBank Corp. (~50% of revenue, ~35% margin), a Japanese mobile and broadband operator, and ARM Holdings (~30% of revenue, ~35% operating margin), which licenses chip architecture IP to virtually every major semiconductor manufacturer with near-monopoly positioning in mobile and fast-growing exposure to AI datacenters. The remaining segments — Vision Funds and Investment Business of Holding Companies — generate no direct revenue but drive reported earnings through mark-to-market fair-value movements on key direct stakes (ARM ~90%, OpenAI ~11%, SoftBank Corp. ~40%, Ampere Computing 100%) and Vision Fund holdings (Coupang, ByteDance, Swiggy).$F$,
  'Deteriorating', 'Low', 'Weak',
  $F$SoftBank's competitive advantage is narrow. ARM provides a genuine moat — near-monopoly chip architecture IP with high switching costs across mobile and AI datacenters. Beyond that, SoftBank benefits from Son's elite network (OpenAI, Saudi PIF, heads of state) and the ability to write $30bn+ single checks, giving access to deals no traditional fund can match.
However, the investment model itself is replicable, there is no proprietary dealflow or technology at holding level, and Son's track record is inconsistent — Alibaba (brilliant), WeWork (disastrous), Nvidia (sold too early).$F$,
  'Niche',
  4, '6.60', 3,
  10.14, 163.93, 8.89, 'Above',
  $F$Prosus$F$, 'Premium',
  '534.81', '3.84%', '-$53.28', 3,
  'Uptrend', 'Bullish', 'Buy', 4,
  'Long', 4400.00, 6700.00, 3200.00, 0,
  2.00, 4,
  17, 5,
  $F$SoftBank is not a fundamentally sound investment. The company generates no meaningful recurring earnings — reported profits are almost entirely mark-to-market revaluations of portfolio stakes, not cash. There is no strong moat at holding level beyond ARM. The balance sheet runs on debt and asset sales, with LTV approaching its internal limit and most liquid assets already monetized. With ~60-70% of NAV concentrated in ARM and OpenAI, the thesis is binary: AI valuations keep rising, or they don't. At its core, SoftBank is a leveraged bet on the AI narrative — not a business$F$,
  '2026-05-05 20:20:00+00', 5
)
ON CONFLICT (trading_id) DO UPDATE SET
  company_name = EXCLUDED.company_name, status = EXCLUDED.status, ticker = EXCLUDED.ticker,
  date_of_case = EXCLUDED.date_of_case, sector = EXCLUDED.sector, industry = EXCLUDED.industry,
  country_of_incorporation = EXCLUDED.country_of_incorporation,
  current_price_at_case = EXCLUDED.current_price_at_case,
  week_52_high = EXCLUDED.week_52_high, week_52_low = EXCLUDED.week_52_low,
  analyst_1y_price_target = EXCLUDED.analyst_1y_price_target,
  event_summary = EXCLUDED.event_summary, event_type = EXCLUDED.event_type,
  event_classification = EXCLUDED.event_classification, impact_of_news = EXCLUDED.impact_of_news,
  initial_market_assessment = EXCLUDED.initial_market_assessment,
  catalyst_1 = EXCLUDED.catalyst_1, catalyst_2 = EXCLUDED.catalyst_2,
  catalyst_3 = EXCLUDED.catalyst_3, catalyst_4 = EXCLUDED.catalyst_4,
  trigger_score = EXCLUDED.trigger_score,
  risk_1 = EXCLUDED.risk_1, risk_2 = EXCLUDED.risk_2,
  risk_3 = EXCLUDED.risk_3, risk_4 = EXCLUDED.risk_4,
  business_model_explanation = EXCLUDED.business_model_explanation,
  key_products_services = EXCLUDED.key_products_services,
  business_model_outlook = EXCLUDED.business_model_outlook,
  earnings_quality = EXCLUDED.earnings_quality, competitive_advantage = EXCLUDED.competitive_advantage,
  competitive_advantage_defined = EXCLUDED.competitive_advantage_defined,
  market_position = EXCLUDED.market_position,
  esg_governance_quality_score = EXCLUDED.esg_governance_quality_score,
  net_debt_ebitda = EXCLUDED.net_debt_ebitda,
  fundamental_score = EXCLUDED.fundamental_score,
  current_pe = EXCLUDED.current_pe, forward_pe = EXCLUDED.forward_pe, ev_ebitda = EXCLUDED.ev_ebitda,
  current_vs_historical_multiples = EXCLUDED.current_vs_historical_multiples,
  top_3_competitors = EXCLUDED.top_3_competitors,
  prior_valuation_assessment = EXCLUDED.prior_valuation_assessment,
  eps = EXCLUDED.eps, operating_margin = EXCLUDED.operating_margin,
  layered_fcf_ttm = EXCLUDED.layered_fcf_ttm,
  valuation_score = EXCLUDED.valuation_score,
  primary_trend = EXCLUDED.primary_trend, overall_chart_assessment = EXCLUDED.overall_chart_assessment,
  tradingview_ta_score = EXCLUDED.tradingview_ta_score,
  technical_score = EXCLUDED.technical_score,
  direction = EXCLUDED.direction, entry_price_target = EXCLUDED.entry_price_target,
  take_profit = EXCLUDED.take_profit, stop_loss = EXCLUDED.stop_loss, leverage = EXCLUDED.leverage,
  risk_reward_ratio = EXCLUDED.risk_reward_ratio,
  expected_holding_period_months = EXCLUDED.expected_holding_period_months,
  total_score = EXCLUDED.total_score, confidence_score = EXCLUDED.confidence_score,
  why_not_executed = EXCLUDED.why_not_executed,
  created_at = EXCLUDED.created_at, conviction_score = EXCLUDED.conviction_score;


-- 12. Avantium (AVTX-7-0526) — Not Active
INSERT INTO public.cases (
  trading_id, company_name, status, ticker, date_of_case, sector, industry, country_of_incorporation,
  current_price_at_case, week_52_high, week_52_low, analyst_1y_price_target,
  event_summary, event_type, event_classification, impact_of_news, initial_market_assessment,
  catalyst_1, catalyst_2, catalyst_3, catalyst_4, trigger_score,
  risk_1, risk_2, risk_3, risk_4,
  business_model_explanation, key_products_services, business_model_outlook,
  earnings_quality, competitive_advantage, competitive_advantage_defined, market_position,
  fundamental_score,
  current_vs_historical_multiples,
  top_3_competitors, prior_valuation_assessment,
  eps, operating_margin, layered_fcf_ttm, valuation_score,
  primary_trend, overall_chart_assessment, tradingview_ta_score, technical_score,
  direction, entry_price_target, take_profit, stop_loss, leverage,
  risk_reward_ratio, expected_holding_period_months,
  total_score, confidence_score, execute, created_at, conviction_score
) VALUES (
  'AVTX-7-0526', $F$Avantium$F$, 'Not Active', 'AVTX', '2026-05-13',
  'Basic Materials', 'Specialty Chemicals', 'NL',
  7.90, 13.20, 5.86, 30.00,
  $F$Avantium's decline from €40 to €7 since 2020 is not a story of failed technology but of chronic execution failure and repeated dilution. The Delfzijl plant was promised for 2023, then 2024, then Q1 2026 — each delay forcing the company back to capital markets, raising equity five times since 2021 and increasing the share count by 76% in a single year. Meanwhile, the only licensing deal signed (Origin Materials) was partially suspended in 2024, cashburn remained at €48M/year against just €21M revenue, and a hostile macro environment from 2022 onwards punished all pre-profitable green-tech companies. Multiple CFO and COO changes during the most critical phase completed the picture.$F$,
  $F$Guidance updates,Sentiment risk,Balance sheet updates,Earnings$F$, 'Non-recurring', 'Structural', 'Justified',
  $F$First commercial FDCA sale — the moment the first batch is delivered under an offtake agreement, it proves the technology at industrial scale and completely shifts market sentiment.$F$,
  $F$If new licensing deal signed — a single large-scale YXY® license to an industrial partner validates the business model and creates direct visibility on future royalty income.$F$,
  $F$Dutch government funding confirmed — a hard commitment removes the largest remaining financing uncertainty and takes dilution risk off the table.$F$,
  $F$FDCA Flagship Plant fully operational in H2 2026 — the most immediate and critical catalyst. Weld repairs completed (April 30), oxidation and purification units still being commissioned. If the plant reaches stable commercial production this year and delivers first batches under existing offtake agreements, it proves the technology at industrial scale, reduces cashburn, and fundamentally changes the investment narrative from "pre-commercial promise" to "operational company."$F$,
  4,
  $F$Plants delays again — oxidation/purification units still not operational, cash runway expires end 2026/early 2027. One more major delay equals a financing crisis and likely further dilution$F$,
  $F$Dilution — lender warrants exercisable at €1 nominal remain outstanding. If the plant underdelivers and new financing is needed, existing shareholders get further diluted.$F$,
  $F$GS Biomats scales faster — if the Chinese competitor delivers large-scale cheap FDCA first, it undermines Avantium's licensing pipeline and pricing power before it even gets started.$F$,
  $F$ESG tailwind reverses — the entire business model relies on corporate sustainability commitments and supportive regulation. If political sentiment shifts further away from ESG, demand for premium biobased materials weakens.$F$,
  $F$Avantium operates through two business units. The first, R&D Solutions, sells advanced laboratory equipment and catalyst testing systems to chemical companies worldwide, generating ~€15M in stable annual revenue. The second, Renewable Polymers, is the core growth bet: Avantium developed the proprietary YXY® Technology that converts plant-based sugars into FDCA, the building block for PEF — a 100% plant-based, recyclable plastic that outperforms fossil-based PET in barrier properties. Revenue from this segment comes from three sources: direct FDCA and PEF sales from its 5,000 tonne/year flagship plant in Delfzijl, technology licensing fees from industrial partners who build their own FDCA plants using Avantium's IP, and capacity reservations. The licensing model is the long-term prize — capital-light, high-margin, and globally scalable — with the Delfzijl plant primarily serving as commercial proof of concept to unlock that licensing pipeline.$F$,
  $F$Avantium operates two revenue streams. R&D Solutions contributes ~70% of current revenue (~€14M of €21M total in 2024) through sales of proprietary catalyst testing equipment and R&D services to chemical companies. Renewable Polymers contributes the remaining ~30%, currently almost entirely from the Origin Materials licensing deal rather than actual product sales. In the bull scenario, this flips entirely: once the Delfzijl plant runs at full capacity, direct FDCA and PEF sales could generate €20-30M annually, while a single large-scale YXY® technology license to an industrial partner could generate tens of millions in upfront fees plus ongoing royalties — management targets €100M+ revenue and EBITDA profitability by 2027.$F$,
  'Strong', 'High', 'Moderate',
  $F$Avantium's moat is real but narrow. The company has 20+ years of FDCA/PEF R&D, 179+ patent families protecting YXY® Technology, the world's first commercial FDCA plant, and 20+ signed offtake agreements with premium brand owners like LVMH, Carlsberg and Henkel — creating genuine first-mover credibility and switching costs.
However, GS Biomats (China) has developed its own independent FDCA technology, is building a 10,000 tonne/year plant (double Avantium's capacity), and already claims 200+ tonnes delivered commercially. Chinese manufacturing cost advantages could allow them to undercut Avantium on price for commodity applications.
Avantium's defensibility ultimately rests on its IP, Western market relationships, and product quality premium — but the window to lock in licensing deals before competitors establish scale is closing fast.$F$,
  'Leader',
  5,
  'Significant below',
  $F$GS Biomats, Corbion, NatureWorks$F$, 'Discounted',
  '-1.70', '-249.07%', '-$0.48', 4,
  'Strong downtrend', 'Bearish', 'Buy', 3,
  'Long', 7.35, 22.50, 6.35, 0,
  5.00, 12,
  25, 6, true, '2026-05-13 16:47:00+00', 9
)
ON CONFLICT (trading_id) DO UPDATE SET
  company_name = EXCLUDED.company_name, status = EXCLUDED.status, ticker = EXCLUDED.ticker,
  date_of_case = EXCLUDED.date_of_case, sector = EXCLUDED.sector, industry = EXCLUDED.industry,
  country_of_incorporation = EXCLUDED.country_of_incorporation,
  current_price_at_case = EXCLUDED.current_price_at_case,
  week_52_high = EXCLUDED.week_52_high, week_52_low = EXCLUDED.week_52_low,
  analyst_1y_price_target = EXCLUDED.analyst_1y_price_target,
  event_summary = EXCLUDED.event_summary, event_type = EXCLUDED.event_type,
  event_classification = EXCLUDED.event_classification, impact_of_news = EXCLUDED.impact_of_news,
  initial_market_assessment = EXCLUDED.initial_market_assessment,
  catalyst_1 = EXCLUDED.catalyst_1, catalyst_2 = EXCLUDED.catalyst_2,
  catalyst_3 = EXCLUDED.catalyst_3, catalyst_4 = EXCLUDED.catalyst_4,
  trigger_score = EXCLUDED.trigger_score,
  risk_1 = EXCLUDED.risk_1, risk_2 = EXCLUDED.risk_2,
  risk_3 = EXCLUDED.risk_3, risk_4 = EXCLUDED.risk_4,
  business_model_explanation = EXCLUDED.business_model_explanation,
  key_products_services = EXCLUDED.key_products_services,
  business_model_outlook = EXCLUDED.business_model_outlook,
  earnings_quality = EXCLUDED.earnings_quality, competitive_advantage = EXCLUDED.competitive_advantage,
  competitive_advantage_defined = EXCLUDED.competitive_advantage_defined,
  market_position = EXCLUDED.market_position,
  fundamental_score = EXCLUDED.fundamental_score,
  current_vs_historical_multiples = EXCLUDED.current_vs_historical_multiples,
  top_3_competitors = EXCLUDED.top_3_competitors,
  prior_valuation_assessment = EXCLUDED.prior_valuation_assessment,
  eps = EXCLUDED.eps, operating_margin = EXCLUDED.operating_margin,
  layered_fcf_ttm = EXCLUDED.layered_fcf_ttm,
  valuation_score = EXCLUDED.valuation_score,
  primary_trend = EXCLUDED.primary_trend, overall_chart_assessment = EXCLUDED.overall_chart_assessment,
  tradingview_ta_score = EXCLUDED.tradingview_ta_score,
  technical_score = EXCLUDED.technical_score,
  direction = EXCLUDED.direction, entry_price_target = EXCLUDED.entry_price_target,
  take_profit = EXCLUDED.take_profit, stop_loss = EXCLUDED.stop_loss, leverage = EXCLUDED.leverage,
  risk_reward_ratio = EXCLUDED.risk_reward_ratio,
  expected_holding_period_months = EXCLUDED.expected_holding_period_months,
  total_score = EXCLUDED.total_score, confidence_score = EXCLUDED.confidence_score,
  execute = EXCLUDED.execute, created_at = EXCLUDED.created_at,
  conviction_score = EXCLUDED.conviction_score;


-- ─── Done. Verify with: SELECT trading_id, company_name, status FROM public.cases ORDER BY date_of_case; ───
