// Atlas & Sage tool registry — three-tier risk model ported from Otto.
//
//   risk='read'          → pure data fetch, auto-runs.
//   risk='auto_write'    → reversible mutation, auto-runs and emits an
//                          action-chip in the UI.
//   risk='propose_write' → destructive mutation. The streaming route stages
//                          it as a chat_write_actions row and shows a plan
//                          card; the user explicitly approves before the
//                          handler is called.
//
// Sage only sees risk='read' tools; Atlas sees everything where surface
// includes 'atlas'.

import { z, type ZodTypeAny } from 'zod'
import { createClient } from '@supabase/supabase-js'
import type { AgentSurface, AgentRisk, PlanDiff } from './types'

function service() {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
  )
}

export interface ToolContext {
  userId: string
  agent: 'atlas' | 'sage'
}

export interface ToolDef<I = unknown, R = unknown> {
  name: string
  description: string
  // Anthropic-compatible JSON schema. Generated by hand because we want
  // descriptions that read well to the LLM, not derived from Zod.
  input_schema: Record<string, unknown>
  // Server-side runtime validation. Belts-and-braces — Anthropic occasionally
  // omits required fields when a model is confused, and we want a clean
  // error instead of a database 500.
  schema: ZodTypeAny
  risk: AgentRisk
  surface: AgentSurface
  handler: (input: I, ctx: ToolContext) => Promise<R>
  // Only present for risk='propose_write'. Builds the structured diff
  // shown on the plan card before the user approves.
  buildDiff?: (input: I, ctx: ToolContext) => Promise<PlanDiff>
}

// ─── READ tools ────────────────────────────────────────────────────────

const listCasesSchema = z.object({
  status: z.enum(['Active', 'Not Active']).optional(),
})

const listCases: ToolDef<z.infer<typeof listCasesSchema>> = {
  name: 'list_cases',
  description: 'List all investment cases with a compact summary. Useful for finding the right trading_id before editing.',
  input_schema: {
    type: 'object',
    properties: {
      status: { type: 'string', enum: ['Active', 'Not Active'], description: 'Optional status filter.' },
    },
  },
  schema: listCasesSchema,
  risk: 'read',
  surface: 'both',
  async handler(input) {
    let q = service().from('cases').select('trading_id, ticker, company_name, sector, status, total_score, take_profit, stop_loss, expected_holding_period_months, date_of_case')
    if (input.status) q = q.eq('status', input.status)
    const { data, error } = await q.order('date_of_case', { ascending: false })
    if (error) throw new Error(error.message)
    return data ?? []
  },
}

const getCaseSchema = z.object({ trading_id: z.string().min(1) })
const getCase: ToolDef<z.infer<typeof getCaseSchema>> = {
  name: 'get_case',
  description: 'Get the full record of one case by trading_id, including every field.',
  input_schema: {
    type: 'object',
    required: ['trading_id'],
    properties: { trading_id: { type: 'string' } },
  },
  schema: getCaseSchema,
  risk: 'read',
  surface: 'both',
  async handler(input) {
    const { data, error } = await service().from('cases').select('*').eq('trading_id', input.trading_id).maybeSingle()
    if (error) throw new Error(error.message)
    if (!data) throw new Error(`No case found with trading_id "${input.trading_id}"`)
    return data
  },
}

const lookupSymSchema = z.object({ symbol: z.string().min(1).max(20) })
const lookupCaseBySymbol: ToolDef<z.infer<typeof lookupSymSchema>> = {
  name: 'lookup_case_by_symbol',
  description: 'Find the case (and its trading_id) for a ticker. Use this to translate "MSFT" → trading_id before editing.',
  input_schema: {
    type: 'object',
    required: ['symbol'],
    properties: { symbol: { type: 'string', description: 'Ticker like MSFT, ORCL, etc.' } },
  },
  schema: lookupSymSchema,
  risk: 'read',
  surface: 'both',
  async handler(input) {
    const symbol = input.symbol.toUpperCase()
    const supabase = service()
    const { data: pos } = await supabase
      .from('open_positions')
      .select('symbol, trading_id')
      .ilike('symbol', symbol)
      .maybeSingle()
    if (pos?.trading_id) {
      const { data: c } = await supabase.from('cases').select('trading_id, ticker, company_name, status').eq('trading_id', pos.trading_id).maybeSingle()
      return { matched_via: 'open_position', ...c }
    }
    const { data: c2 } = await supabase
      .from('cases')
      .select('trading_id, ticker, company_name, status')
      .ilike('ticker', symbol)
      .limit(5)
    return { matched_via: 'ticker', candidates: c2 ?? [] }
  },
}

const listPositionsSchema = z.object({})
const listPositions: ToolDef<z.infer<typeof listPositionsSchema>> = {
  name: 'list_positions',
  description: 'List all currently open positions with symbol, trading_id, P&L and last sync time.',
  input_schema: { type: 'object', properties: {} },
  schema: listPositionsSchema,
  risk: 'read',
  surface: 'both',
  async handler() {
    const { data, error } = await service()
      .from('open_positions')
      .select('symbol, trading_id, entry_price_actual, current_price, position_size_actual, unrealized_pnl, unrealized_pnl_pct, pct_of_nav, entry_date_actual, last_synced_at')
    if (error) throw new Error(error.message)
    return data ?? []
  },
}

const portfolioSummarySchema = z.object({})
const getPortfolioSummary: ToolDef<z.infer<typeof portfolioSummarySchema>> = {
  name: 'get_portfolio_summary',
  description: 'High-level portfolio snapshot: total NAV, latest TWR, # open positions, latest M² risk-adjusted return.',
  input_schema: { type: 'object', properties: {} },
  schema: portfolioSummarySchema,
  risk: 'read',
  surface: 'both',
  async handler() {
    const supabase = service()
    const [{ data: positions }, { data: snaps }, { data: rates }] = await Promise.all([
      supabase.from('open_positions').select('symbol, current_price, position_size_actual, unrealized_pnl'),
      supabase.from('portfolio_snapshots').select('snapshot_date, total_nav, benchmark_value, daily_twr').order('snapshot_date', { ascending: true }),
      supabase.from('risk_free_rates').select('rate').order('date', { ascending: false }).limit(1),
    ])
    const totalNav = (positions ?? []).reduce((s, p) => s + (p.current_price * p.position_size_actual), 0)
    const totalUnrealized = (positions ?? []).reduce((s, p) => s + (p.unrealized_pnl ?? 0), 0)
    let twrFactor = 1
    for (const s of snaps ?? []) twrFactor *= 1 + (s.daily_twr ?? 0) / 100
    return {
      total_nav_eur: totalNav,
      total_unrealized_pnl_eur: totalUnrealized,
      open_positions_count: positions?.length ?? 0,
      twr_since_inception_pct: (twrFactor - 1) * 100,
      latest_risk_free_rate_pct: rates?.[0] ? Number(rates[0].rate) * 100 : null,
      snapshots_count: snaps?.length ?? 0,
    }
  },
}

const perfHistorySchema = z.object({
  days: z.number().int().min(7).max(3650).default(180),
})
const getPerformanceHistory: ToolDef<z.infer<typeof perfHistorySchema>> = {
  name: 'get_performance_history',
  description: 'Time-series of portfolio NAV, benchmark value and daily TWR. Use this when the user asks "how did the portfolio do" — you can wrap the result in a <chart-spec> block to draw a line chart.',
  input_schema: {
    type: 'object',
    properties: { days: { type: 'integer', minimum: 7, maximum: 3650, description: 'Trailing window size in days (default 180).' } },
  },
  schema: perfHistorySchema,
  risk: 'read',
  surface: 'both',
  async handler(input) {
    const since = new Date()
    since.setDate(since.getDate() - input.days)
    const { data, error } = await service()
      .from('portfolio_snapshots')
      .select('snapshot_date, total_nav, benchmark_value, daily_twr')
      .gte('snapshot_date', since.toISOString().slice(0, 10))
      .order('snapshot_date', { ascending: true })
    if (error) throw new Error(error.message)
    return { days: input.days, points: data ?? [] }
  },
}

const closedTradesSchema = z.object({
  limit: z.number().int().min(1).max(200).default(20),
})
const getClosedTrades: ToolDef<z.infer<typeof closedTradesSchema>> = {
  name: 'get_closed_trades',
  description: 'List the most recently closed trades with entry/exit price, P&L and holding period.',
  input_schema: {
    type: 'object',
    properties: { limit: { type: 'integer', minimum: 1, maximum: 200, description: 'Max rows (default 20).' } },
  },
  schema: closedTradesSchema,
  risk: 'read',
  surface: 'both',
  async handler(input) {
    const { data, error } = await service()
      .from('closed_trades')
      .select('symbol, trading_id, entry_date, exit_date, entry_price, exit_price, realized_pnl, realized_pnl_pct, holding_period_days')
      .order('exit_date', { ascending: false })
      .limit(input.limit)
    if (error) {
      // closed_trades may not exist on every deployment yet — degrade
      // gracefully so the LLM can fall back to other tools.
      if (/relation .* does not exist/i.test(error.message)) return { rows: [], note: 'closed_trades table not yet provisioned' }
      throw new Error(error.message)
    }
    return { rows: data ?? [] }
  },
}

// ─── AUTO-WRITE tools ─────────────────────────────────────────────────

const refreshBundSchema = z.object({})
const refreshBundData: ToolDef<z.infer<typeof refreshBundSchema>> = {
  name: 'refresh_bund_data',
  description: 'Refresh the 10Y German Bund yield from Bundesbank (R_f for the Capped M² calculation). Auto-runs — purely an upsert into risk_free_rates.',
  input_schema: { type: 'object', properties: {} },
  schema: refreshBundSchema,
  risk: 'auto_write',
  surface: 'atlas',
  async handler() {
    const url = 'https://api.statistiken.bundesbank.de/rest/data/BBSIS/D.I.ZAR.ZI.EUR.S1311.B.A604.R10XX.R.A.A._Z._Z.A?format=csv&lang=en'
    const res = await fetch(url, { headers: { 'User-Agent': 'fynoy-capital-atlas/1.0' } })
    if (!res.ok) throw new Error(`Bundesbank: ${res.status}`)
    const csv = await res.text()
    const rows: { date: string; rate: number }[] = []
    for (const rawLine of csv.split(/\r?\n/)) {
      const line = rawLine.trim()
      if (!line) continue
      const cells = line.split(/[;,]/).map(c => c.replace(/^"|"$/g, '').trim())
      const di = cells.findIndex(c => /^\d{4}-\d{2}-\d{2}$/.test(c))
      if (di === -1) continue
      let rate: number | null = null
      for (let i = di + 1; i < cells.length; i++) {
        const v = cells[i].replace(',', '.')
        if (v === '' || v === '.' || v === '-') continue
        const num = Number(v)
        if (Number.isFinite(num)) { rate = num; break }
      }
      if (rate === null) continue
      rows.push({ date: cells[di], rate: rate / 100 })
    }
    if (rows.length === 0) throw new Error('No parseable rows in Bundesbank response')
    const records = rows.map(r => ({ date: r.date, rate: r.rate, source: 'bundesbank-BBSIS-10Y', updated_at: new Date().toISOString() }))
    const { error } = await service().from('risk_free_rates').upsert(records, { onConflict: 'date' })
    if (error) throw new Error(error.message)
    const last = rows[rows.length - 1]
    return { updated: rows.length, latest_date: last.date, latest_rate_pct: (last.rate * 100).toFixed(3) }
  },
}

// ─── PROPOSE-WRITE tools (plan card → user approval) ─────────────────

const updateCaseSchema = z.object({
  trading_id: z.string().min(1),
  updates: z.record(z.unknown()).refine(o => Object.keys(o).length > 0, 'updates must not be empty'),
})
const updateCase: ToolDef<z.infer<typeof updateCaseSchema>> = {
  name: 'update_case',
  description: 'Update one or more fields on a case. Pass the trading_id and an object of fields to change. The user reviews a diff before this runs. Use exact column names from the cases table (take_profit, stop_loss, expected_holding_period_months, status, conviction_score, etc.).',
  input_schema: {
    type: 'object',
    required: ['trading_id', 'updates'],
    properties: {
      trading_id: { type: 'string' },
      updates: {
        type: 'object',
        description: 'Fields to update — e.g. { take_profit: 520, stop_loss: 380 }.',
        additionalProperties: true,
      },
    },
  },
  schema: updateCaseSchema,
  risk: 'propose_write',
  surface: 'atlas',
  async buildDiff(input) {
    const { data: current, error } = await service()
      .from('cases')
      .select('*')
      .eq('trading_id', input.trading_id)
      .maybeSingle()
    if (error) throw new Error(error.message)
    if (!current) throw new Error(`No case with trading_id "${input.trading_id}"`)
    const changes = Object.entries(input.updates).map(([field, to]) => ({
      field,
      from: (current as Record<string, unknown>)[field] ?? null,
      to,
    }))
    return {
      kind: 'case_update',
      trading_id: input.trading_id,
      ticker: current.ticker ?? null,
      company_name: current.company_name ?? null,
      changes,
    }
  },
  async handler(input) {
    const { data, error } = await service()
      .from('cases')
      .update({ ...input.updates, updated_at: new Date().toISOString() })
      .eq('trading_id', input.trading_id)
      .select()
      .maybeSingle()
    if (error) throw new Error(error.message)
    if (!data) throw new Error(`No case updated — trading_id "${input.trading_id}" not found`)
    return { updated_fields: Object.keys(input.updates), case: data }
  },
}

const updatePositionSchema = z.object({
  symbol: z.string().min(1),
  updates: z.record(z.unknown()).refine(o => Object.keys(o).length > 0, 'updates must not be empty'),
})
const updatePosition: ToolDef<z.infer<typeof updatePositionSchema>> = {
  name: 'update_position',
  description: 'Update fields on an open position (rarely needed — most edits should go to the linked case via update_case). Use only for things like manual entry_price_actual corrections.',
  input_schema: {
    type: 'object',
    required: ['symbol', 'updates'],
    properties: {
      symbol: { type: 'string' },
      updates: { type: 'object', additionalProperties: true },
    },
  },
  schema: updatePositionSchema,
  risk: 'propose_write',
  surface: 'atlas',
  async buildDiff(input) {
    const sym = input.symbol.toUpperCase()
    const { data: current, error } = await service()
      .from('open_positions')
      .select('*')
      .ilike('symbol', sym)
      .maybeSingle()
    if (error) throw new Error(error.message)
    if (!current) throw new Error(`No open position with symbol "${sym}"`)
    const changes = Object.entries(input.updates).map(([field, to]) => ({
      field,
      from: (current as Record<string, unknown>)[field] ?? null,
      to,
    }))
    return { kind: 'position_update', symbol: sym, changes }
  },
  async handler(input) {
    const sym = input.symbol.toUpperCase()
    const { data, error } = await service()
      .from('open_positions')
      .update(input.updates)
      .ilike('symbol', sym)
      .select()
      .maybeSingle()
    if (error) throw new Error(error.message)
    if (!data) throw new Error(`No position with symbol "${sym}"`)
    return { updated_fields: Object.keys(input.updates), position: data }
  },
}

// ─── Registry ─────────────────────────────────────────────────────────

export const ALL_TOOLS: ToolDef[] = [
  // read
  listCases, getCase, lookupCaseBySymbol, listPositions, getPortfolioSummary,
  getPerformanceHistory, getClosedTrades,
  // auto_write
  refreshBundData,
  // propose_write
  updateCase, updatePosition,
] as ToolDef[]

export function toolsForAgent(agent: 'atlas' | 'sage'): ToolDef[] {
  return ALL_TOOLS.filter(t => t.surface === 'both' || t.surface === agent).filter(t =>
    // Sage gets only read tools; defence in depth even if the registry is mis-tagged.
    agent === 'atlas' ? true : t.risk === 'read',
  )
}

export function getTool(name: string, agent: 'atlas' | 'sage'): ToolDef | undefined {
  return toolsForAgent(agent).find(t => t.name === name)
}

export function toolsForApi(agent: 'atlas' | 'sage'): { name: string; description: string; input_schema: Record<string, unknown> }[] {
  return toolsForAgent(agent).map(t => ({
    name: t.name,
    description: t.description,
    input_schema: t.input_schema,
  }))
}
